// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/motion_sim.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'services/motion_sim/model.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<SimulatorUpdate> dco_decode_StreamSink_simulator_update_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AccelerometerData dco_decode_accelerometer_data(dynamic raw);

  @protected
  BarometerData dco_decode_barometer_data(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AccelerometerData dco_decode_box_autoadd_accelerometer_data(dynamic raw);

  @protected
  BarometerData dco_decode_box_autoadd_barometer_data(dynamic raw);

  @protected
  Checkpoint dco_decode_box_autoadd_checkpoint(dynamic raw);

  @protected
  Command dco_decode_box_autoadd_command(dynamic raw);

  @protected
  CompassData dco_decode_box_autoadd_compass_data(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  GeoPoint dco_decode_box_autoadd_geo_point(dynamic raw);

  @protected
  GpsData dco_decode_box_autoadd_gps_data(dynamic raw);

  @protected
  GyroscopeData dco_decode_box_autoadd_gyroscope_data(dynamic raw);

  @protected
  PedometerData dco_decode_box_autoadd_pedometer_data(dynamic raw);

  @protected
  Polygon dco_decode_box_autoadd_polygon(dynamic raw);

  @protected
  SensorData dco_decode_box_autoadd_sensor_data(dynamic raw);

  @protected
  SimulatorConfig dco_decode_box_autoadd_simulator_config(dynamic raw);

  @protected
  SimulatorEvent dco_decode_box_autoadd_simulator_event(dynamic raw);

  @protected
  SimulatorState dco_decode_box_autoadd_simulator_state(dynamic raw);

  @protected
  SimulatorStats dco_decode_box_autoadd_simulator_stats(dynamic raw);

  @protected
  Trajectory dco_decode_box_autoadd_trajectory(dynamic raw);

  @protected
  Checkpoint dco_decode_checkpoint(dynamic raw);

  @protected
  Command dco_decode_command(dynamic raw);

  @protected
  CommandResult dco_decode_command_result(dynamic raw);

  @protected
  CompassData dco_decode_compass_data(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  GeoPoint dco_decode_geo_point(dynamic raw);

  @protected
  GpsData dco_decode_gps_data(dynamic raw);

  @protected
  GyroscopeData dco_decode_gyroscope_data(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<Checkpoint> dco_decode_list_checkpoint(dynamic raw);

  @protected
  List<GeoPoint> dco_decode_list_geo_point(dynamic raw);

  @protected
  List<Polygon> dco_decode_list_polygon(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Trajectory> dco_decode_list_trajectory(dynamic raw);

  @protected
  MovementPhase dco_decode_movement_phase(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AccelerometerData? dco_decode_opt_box_autoadd_accelerometer_data(dynamic raw);

  @protected
  BarometerData? dco_decode_opt_box_autoadd_barometer_data(dynamic raw);

  @protected
  CompassData? dco_decode_opt_box_autoadd_compass_data(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  GeoPoint? dco_decode_opt_box_autoadd_geo_point(dynamic raw);

  @protected
  GpsData? dco_decode_opt_box_autoadd_gps_data(dynamic raw);

  @protected
  GyroscopeData? dco_decode_opt_box_autoadd_gyroscope_data(dynamic raw);

  @protected
  PedometerData? dco_decode_opt_box_autoadd_pedometer_data(dynamic raw);

  @protected
  Polygon? dco_decode_opt_box_autoadd_polygon(dynamic raw);

  @protected
  SensorData? dco_decode_opt_box_autoadd_sensor_data(dynamic raw);

  @protected
  SimulatorConfig? dco_decode_opt_box_autoadd_simulator_config(dynamic raw);

  @protected
  SimulatorState? dco_decode_opt_box_autoadd_simulator_state(dynamic raw);

  @protected
  SimulatorStats? dco_decode_opt_box_autoadd_simulator_stats(dynamic raw);

  @protected
  PedometerData dco_decode_pedometer_data(dynamic raw);

  @protected
  Polygon dco_decode_polygon(dynamic raw);

  @protected
  SensorData dco_decode_sensor_data(dynamic raw);

  @protected
  SimulatorConfig dco_decode_simulator_config(dynamic raw);

  @protected
  SimulatorEvent dco_decode_simulator_event(dynamic raw);

  @protected
  SimulatorState dco_decode_simulator_state(dynamic raw);

  @protected
  SimulatorStats dco_decode_simulator_stats(dynamic raw);

  @protected
  SimulatorUpdate dco_decode_simulator_update(dynamic raw);

  @protected
  StopReason dco_decode_stop_reason(dynamic raw);

  @protected
  Trajectory dco_decode_trajectory(dynamic raw);

  @protected
  TrajectoryMode dco_decode_trajectory_mode(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<SimulatorUpdate> sse_decode_StreamSink_simulator_update_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AccelerometerData sse_decode_accelerometer_data(SseDeserializer deserializer);

  @protected
  BarometerData sse_decode_barometer_data(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AccelerometerData sse_decode_box_autoadd_accelerometer_data(
    SseDeserializer deserializer,
  );

  @protected
  BarometerData sse_decode_box_autoadd_barometer_data(
    SseDeserializer deserializer,
  );

  @protected
  Checkpoint sse_decode_box_autoadd_checkpoint(SseDeserializer deserializer);

  @protected
  Command sse_decode_box_autoadd_command(SseDeserializer deserializer);

  @protected
  CompassData sse_decode_box_autoadd_compass_data(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  GeoPoint sse_decode_box_autoadd_geo_point(SseDeserializer deserializer);

  @protected
  GpsData sse_decode_box_autoadd_gps_data(SseDeserializer deserializer);

  @protected
  GyroscopeData sse_decode_box_autoadd_gyroscope_data(
    SseDeserializer deserializer,
  );

  @protected
  PedometerData sse_decode_box_autoadd_pedometer_data(
    SseDeserializer deserializer,
  );

  @protected
  Polygon sse_decode_box_autoadd_polygon(SseDeserializer deserializer);

  @protected
  SensorData sse_decode_box_autoadd_sensor_data(SseDeserializer deserializer);

  @protected
  SimulatorConfig sse_decode_box_autoadd_simulator_config(
    SseDeserializer deserializer,
  );

  @protected
  SimulatorEvent sse_decode_box_autoadd_simulator_event(
    SseDeserializer deserializer,
  );

  @protected
  SimulatorState sse_decode_box_autoadd_simulator_state(
    SseDeserializer deserializer,
  );

  @protected
  SimulatorStats sse_decode_box_autoadd_simulator_stats(
    SseDeserializer deserializer,
  );

  @protected
  Trajectory sse_decode_box_autoadd_trajectory(SseDeserializer deserializer);

  @protected
  Checkpoint sse_decode_checkpoint(SseDeserializer deserializer);

  @protected
  Command sse_decode_command(SseDeserializer deserializer);

  @protected
  CommandResult sse_decode_command_result(SseDeserializer deserializer);

  @protected
  CompassData sse_decode_compass_data(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  GeoPoint sse_decode_geo_point(SseDeserializer deserializer);

  @protected
  GpsData sse_decode_gps_data(SseDeserializer deserializer);

  @protected
  GyroscopeData sse_decode_gyroscope_data(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<Checkpoint> sse_decode_list_checkpoint(SseDeserializer deserializer);

  @protected
  List<GeoPoint> sse_decode_list_geo_point(SseDeserializer deserializer);

  @protected
  List<Polygon> sse_decode_list_polygon(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Trajectory> sse_decode_list_trajectory(SseDeserializer deserializer);

  @protected
  MovementPhase sse_decode_movement_phase(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AccelerometerData? sse_decode_opt_box_autoadd_accelerometer_data(
    SseDeserializer deserializer,
  );

  @protected
  BarometerData? sse_decode_opt_box_autoadd_barometer_data(
    SseDeserializer deserializer,
  );

  @protected
  CompassData? sse_decode_opt_box_autoadd_compass_data(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  GeoPoint? sse_decode_opt_box_autoadd_geo_point(SseDeserializer deserializer);

  @protected
  GpsData? sse_decode_opt_box_autoadd_gps_data(SseDeserializer deserializer);

  @protected
  GyroscopeData? sse_decode_opt_box_autoadd_gyroscope_data(
    SseDeserializer deserializer,
  );

  @protected
  PedometerData? sse_decode_opt_box_autoadd_pedometer_data(
    SseDeserializer deserializer,
  );

  @protected
  Polygon? sse_decode_opt_box_autoadd_polygon(SseDeserializer deserializer);

  @protected
  SensorData? sse_decode_opt_box_autoadd_sensor_data(
    SseDeserializer deserializer,
  );

  @protected
  SimulatorConfig? sse_decode_opt_box_autoadd_simulator_config(
    SseDeserializer deserializer,
  );

  @protected
  SimulatorState? sse_decode_opt_box_autoadd_simulator_state(
    SseDeserializer deserializer,
  );

  @protected
  SimulatorStats? sse_decode_opt_box_autoadd_simulator_stats(
    SseDeserializer deserializer,
  );

  @protected
  PedometerData sse_decode_pedometer_data(SseDeserializer deserializer);

  @protected
  Polygon sse_decode_polygon(SseDeserializer deserializer);

  @protected
  SensorData sse_decode_sensor_data(SseDeserializer deserializer);

  @protected
  SimulatorConfig sse_decode_simulator_config(SseDeserializer deserializer);

  @protected
  SimulatorEvent sse_decode_simulator_event(SseDeserializer deserializer);

  @protected
  SimulatorState sse_decode_simulator_state(SseDeserializer deserializer);

  @protected
  SimulatorStats sse_decode_simulator_stats(SseDeserializer deserializer);

  @protected
  SimulatorUpdate sse_decode_simulator_update(SseDeserializer deserializer);

  @protected
  StopReason sse_decode_stop_reason(SseDeserializer deserializer);

  @protected
  Trajectory sse_decode_trajectory(SseDeserializer deserializer);

  @protected
  TrajectoryMode sse_decode_trajectory_mode(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_simulator_update_Sse(
    RustStreamSink<SimulatorUpdate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_accelerometer_data(
    AccelerometerData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_barometer_data(BarometerData self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_accelerometer_data(
    AccelerometerData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_barometer_data(
    BarometerData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_checkpoint(
    Checkpoint self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_command(Command self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_compass_data(
    CompassData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_geo_point(
    GeoPoint self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_gps_data(GpsData self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_gyroscope_data(
    GyroscopeData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_pedometer_data(
    PedometerData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_polygon(Polygon self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_sensor_data(
    SensorData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_simulator_config(
    SimulatorConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_simulator_event(
    SimulatorEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_simulator_state(
    SimulatorState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_simulator_stats(
    SimulatorStats self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_trajectory(
    Trajectory self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_checkpoint(Checkpoint self, SseSerializer serializer);

  @protected
  void sse_encode_command(Command self, SseSerializer serializer);

  @protected
  void sse_encode_command_result(CommandResult self, SseSerializer serializer);

  @protected
  void sse_encode_compass_data(CompassData self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_geo_point(GeoPoint self, SseSerializer serializer);

  @protected
  void sse_encode_gps_data(GpsData self, SseSerializer serializer);

  @protected
  void sse_encode_gyroscope_data(GyroscopeData self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_checkpoint(
    List<Checkpoint> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_geo_point(List<GeoPoint> self, SseSerializer serializer);

  @protected
  void sse_encode_list_polygon(List<Polygon> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_trajectory(
    List<Trajectory> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_movement_phase(MovementPhase self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_accelerometer_data(
    AccelerometerData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_barometer_data(
    BarometerData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_compass_data(
    CompassData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_geo_point(
    GeoPoint? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_gps_data(
    GpsData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_gyroscope_data(
    GyroscopeData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_pedometer_data(
    PedometerData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_polygon(
    Polygon? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_sensor_data(
    SensorData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_simulator_config(
    SimulatorConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_simulator_state(
    SimulatorState? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_simulator_stats(
    SimulatorStats? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pedometer_data(PedometerData self, SseSerializer serializer);

  @protected
  void sse_encode_polygon(Polygon self, SseSerializer serializer);

  @protected
  void sse_encode_sensor_data(SensorData self, SseSerializer serializer);

  @protected
  void sse_encode_simulator_config(
    SimulatorConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_simulator_event(
    SimulatorEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_simulator_state(
    SimulatorState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_simulator_stats(
    SimulatorStats self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_simulator_update(
    SimulatorUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stop_reason(StopReason self, SseSerializer serializer);

  @protected
  void sse_encode_trajectory(Trajectory self, SseSerializer serializer);

  @protected
  void sse_encode_trajectory_mode(
    TrajectoryMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
