// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/motion_sim.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'services/motion_sim/model.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -2094800348;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_punklorde',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  String crateApiMotionSimCreateSimulator({
    required SimulatorConfig config,
    required List<Trajectory> trajectories,
  });

  void crateApiMotionSimDisposeSimulator({required String handleId});

  CommandResult crateApiMotionSimExecuteCommand({
    required String handleId,
    required Command command,
  });

  SimulatorConfig? crateApiMotionSimGetConfig({required String handleId});

  SimulatorState? crateApiMotionSimGetState({required String handleId});

  SimulatorStats? crateApiMotionSimGetStats({required String handleId});

  Future<void> crateApiInitApp();

  void crateApiMotionSimPauseSimulator({required String handleId});

  void crateApiMotionSimResumeSimulator({required String handleId});

  void crateApiMotionSimStartSimulator({required String handleId});

  void crateApiMotionSimStopSimulator({
    required String handleId,
    required StopReason reason,
  });

  Future<Stream<SimulatorUpdate>> crateApiMotionSimSubscribeSimulator({
    required String handleId,
  });

  SensorData? crateApiMotionSimUpdateSimulator({
    required String handleId,
    required double dt,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiMotionSimCreateSimulator({
    required SimulatorConfig config,
    required List<Trajectory> trajectories,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_simulator_config(config, serializer);
          sse_encode_list_trajectory(trajectories, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMotionSimCreateSimulatorConstMeta,
        argValues: [config, trajectories],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMotionSimCreateSimulatorConstMeta =>
      const TaskConstMeta(
        debugName: "create_simulator",
        argNames: ["config", "trajectories"],
      );

  @override
  void crateApiMotionSimDisposeSimulator({required String handleId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(handleId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMotionSimDisposeSimulatorConstMeta,
        argValues: [handleId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMotionSimDisposeSimulatorConstMeta =>
      const TaskConstMeta(
        debugName: "dispose_simulator",
        argNames: ["handleId"],
      );

  @override
  CommandResult crateApiMotionSimExecuteCommand({
    required String handleId,
    required Command command,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(handleId, serializer);
          sse_encode_box_autoadd_command(command, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_command_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMotionSimExecuteCommandConstMeta,
        argValues: [handleId, command],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMotionSimExecuteCommandConstMeta =>
      const TaskConstMeta(
        debugName: "execute_command",
        argNames: ["handleId", "command"],
      );

  @override
  SimulatorConfig? crateApiMotionSimGetConfig({required String handleId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(handleId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_simulator_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMotionSimGetConfigConstMeta,
        argValues: [handleId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMotionSimGetConfigConstMeta =>
      const TaskConstMeta(debugName: "get_config", argNames: ["handleId"]);

  @override
  SimulatorState? crateApiMotionSimGetState({required String handleId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(handleId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_simulator_state,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMotionSimGetStateConstMeta,
        argValues: [handleId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMotionSimGetStateConstMeta =>
      const TaskConstMeta(debugName: "get_state", argNames: ["handleId"]);

  @override
  SimulatorStats? crateApiMotionSimGetStats({required String handleId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(handleId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_simulator_stats,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMotionSimGetStatsConstMeta,
        argValues: [handleId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMotionSimGetStatsConstMeta =>
      const TaskConstMeta(debugName: "get_stats", argNames: ["handleId"]);

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  void crateApiMotionSimPauseSimulator({required String handleId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(handleId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMotionSimPauseSimulatorConstMeta,
        argValues: [handleId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMotionSimPauseSimulatorConstMeta =>
      const TaskConstMeta(debugName: "pause_simulator", argNames: ["handleId"]);

  @override
  void crateApiMotionSimResumeSimulator({required String handleId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(handleId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMotionSimResumeSimulatorConstMeta,
        argValues: [handleId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMotionSimResumeSimulatorConstMeta =>
      const TaskConstMeta(
        debugName: "resume_simulator",
        argNames: ["handleId"],
      );

  @override
  void crateApiMotionSimStartSimulator({required String handleId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(handleId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMotionSimStartSimulatorConstMeta,
        argValues: [handleId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMotionSimStartSimulatorConstMeta =>
      const TaskConstMeta(debugName: "start_simulator", argNames: ["handleId"]);

  @override
  void crateApiMotionSimStopSimulator({
    required String handleId,
    required StopReason reason,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(handleId, serializer);
          sse_encode_stop_reason(reason, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMotionSimStopSimulatorConstMeta,
        argValues: [handleId, reason],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMotionSimStopSimulatorConstMeta =>
      const TaskConstMeta(
        debugName: "stop_simulator",
        argNames: ["handleId", "reason"],
      );

  @override
  Future<Stream<SimulatorUpdate>> crateApiMotionSimSubscribeSimulator({
    required String handleId,
  }) async {
    final sink = RustStreamSink<SimulatorUpdate>();
    await handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(handleId, serializer);
          sse_encode_StreamSink_simulator_update_Sse(sink, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMotionSimSubscribeSimulatorConstMeta,
        argValues: [handleId, sink],
        apiImpl: this,
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiMotionSimSubscribeSimulatorConstMeta =>
      const TaskConstMeta(
        debugName: "subscribe_simulator",
        argNames: ["handleId", "sink"],
      );

  @override
  SensorData? crateApiMotionSimUpdateSimulator({
    required String handleId,
    required double dt,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(handleId, serializer);
          sse_encode_f_64(dt, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_sensor_data,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMotionSimUpdateSimulatorConstMeta,
        argValues: [handleId, dt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMotionSimUpdateSimulatorConstMeta =>
      const TaskConstMeta(
        debugName: "update_simulator",
        argNames: ["handleId", "dt"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<SimulatorUpdate> dco_decode_StreamSink_simulator_update_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AccelerometerData dco_decode_accelerometer_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return AccelerometerData(
      x: dco_decode_f_64(arr[0]),
      y: dco_decode_f_64(arr[1]),
      z: dco_decode_f_64(arr[2]),
    );
  }

  @protected
  BarometerData dco_decode_barometer_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BarometerData(
      pressure: dco_decode_f_64(arr[0]),
      relativeAltitude: dco_decode_f_64(arr[1]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AccelerometerData dco_decode_box_autoadd_accelerometer_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_accelerometer_data(raw);
  }

  @protected
  BarometerData dco_decode_box_autoadd_barometer_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_barometer_data(raw);
  }

  @protected
  Checkpoint dco_decode_box_autoadd_checkpoint(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_checkpoint(raw);
  }

  @protected
  Command dco_decode_box_autoadd_command(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_command(raw);
  }

  @protected
  CompassData dco_decode_box_autoadd_compass_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_compass_data(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  GeoPoint dco_decode_box_autoadd_geo_point(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_geo_point(raw);
  }

  @protected
  GpsData dco_decode_box_autoadd_gps_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_gps_data(raw);
  }

  @protected
  GyroscopeData dco_decode_box_autoadd_gyroscope_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_gyroscope_data(raw);
  }

  @protected
  PedometerData dco_decode_box_autoadd_pedometer_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_pedometer_data(raw);
  }

  @protected
  Polygon dco_decode_box_autoadd_polygon(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_polygon(raw);
  }

  @protected
  SensorData dco_decode_box_autoadd_sensor_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_sensor_data(raw);
  }

  @protected
  SimulatorConfig dco_decode_box_autoadd_simulator_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_simulator_config(raw);
  }

  @protected
  SimulatorEvent dco_decode_box_autoadd_simulator_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_simulator_event(raw);
  }

  @protected
  SimulatorState dco_decode_box_autoadd_simulator_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_simulator_state(raw);
  }

  @protected
  SimulatorStats dco_decode_box_autoadd_simulator_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_simulator_stats(raw);
  }

  @protected
  Trajectory dco_decode_box_autoadd_trajectory(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_trajectory(raw);
  }

  @protected
  Checkpoint dco_decode_checkpoint(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return Checkpoint(
      id: dco_decode_String(arr[0]),
      name: dco_decode_opt_String(arr[1]),
      point: dco_decode_opt_box_autoadd_geo_point(arr[2]),
      area: dco_decode_opt_box_autoadd_polygon(arr[3]),
      radius: dco_decode_opt_box_autoadd_f_64(arr[4]),
      mandatory: dco_decode_bool(arr[5]),
      sequence: dco_decode_u_32(arr[6]),
      checked: dco_decode_bool(arr[7]),
    );
  }

  @protected
  Command dco_decode_command(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return Command_SetTargetSpeed(dco_decode_f_64(raw[1]));
      case 1:
        return Command_SetSpeedRange(
          min: dco_decode_f_64(raw[1]),
          max: dco_decode_f_64(raw[2]),
        );
      case 2:
        return Command_SetAcceleration(dco_decode_f_64(raw[1]));
      case 3:
        return Command_SetDeceleration(dco_decode_f_64(raw[1]));
      case 4:
        return Command_SetStepFrequency(dco_decode_f_64(raw[1]));
      case 5:
        return Command_SetStrideLength(dco_decode_f_64(raw[1]));
      case 6:
        return Command_Pause();
      case 7:
        return Command_Resume();
      case 8:
        return Command_StopImmediately();
      case 9:
        return Command_StopAfterFrames(
          frames: dco_decode_u_32(raw[1]),
          graceful: dco_decode_bool(raw[2]),
        );
      case 10:
        return Command_StopAfterTime(
          seconds: dco_decode_f_64(raw[1]),
          graceful: dco_decode_bool(raw[2]),
        );
      case 11:
        return Command_JumpToProgress(dco_decode_f_64(raw[1]));
      case 12:
        return Command_NextTrajectory();
      case 13:
        return Command_AddCheckpoint(dco_decode_box_autoadd_checkpoint(raw[1]));
      case 14:
        return Command_RemoveCheckpoint(dco_decode_String(raw[1]));
      case 15:
        return Command_ClearCheckpoints();
      case 16:
        return Command_ResetCheckpointStatus();
      case 17:
        return Command_SetJitterParams(
          positionAmplitude: dco_decode_opt_box_autoadd_f_64(raw[1]),
          speedAmplitude: dco_decode_opt_box_autoadd_f_64(raw[2]),
          bearingAmplitude: dco_decode_opt_box_autoadd_f_64(raw[3]),
        );
      case 18:
        return Command_SetRefreshRate(
          gps: dco_decode_opt_box_autoadd_f_64(raw[1]),
          accelerometer: dco_decode_opt_box_autoadd_f_64(raw[2]),
          gyroscope: dco_decode_opt_box_autoadd_f_64(raw[3]),
          compass: dco_decode_opt_box_autoadd_f_64(raw[4]),
          barometer: dco_decode_opt_box_autoadd_f_64(raw[5]),
        );
      case 19:
        return Command_SetFenceWarningDistance(dco_decode_f_64(raw[1]));
      case 20:
        return Command_SwitchTrajectory(
          index: dco_decode_usize(raw[1]),
          seamless: dco_decode_bool(raw[2]),
        );
      case 21:
        return Command_AppendTrajectory(
          dco_decode_box_autoadd_trajectory(raw[1]),
        );
      case 22:
        return Command_Custom(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  CommandResult dco_decode_command_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return CommandResult(
      success: dco_decode_bool(arr[0]),
      message: dco_decode_String(arr[1]),
      data: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  CompassData dco_decode_compass_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return CompassData(
      magneticHeading: dco_decode_f_64(arr[0]),
      trueHeading: dco_decode_f_64(arr[1]),
      declination: dco_decode_f_64(arr[2]),
      magneticFieldX: dco_decode_f_64(arr[3]),
      magneticFieldY: dco_decode_f_64(arr[4]),
      magneticFieldZ: dco_decode_f_64(arr[5]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  GeoPoint dco_decode_geo_point(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return GeoPoint(
      latitude: dco_decode_f_64(arr[0]),
      longitude: dco_decode_f_64(arr[1]),
      altitude: dco_decode_opt_box_autoadd_f_64(arr[2]),
    );
  }

  @protected
  GpsData dco_decode_gps_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return GpsData(
      position: dco_decode_geo_point(arr[0]),
      speed: dco_decode_f_64(arr[1]),
      bearing: dco_decode_f_64(arr[2]),
      horizontalAccuracy: dco_decode_f_64(arr[3]),
      verticalAccuracy: dco_decode_f_64(arr[4]),
      satelliteCount: dco_decode_u_8(arr[5]),
    );
  }

  @protected
  GyroscopeData dco_decode_gyroscope_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return GyroscopeData(
      x: dco_decode_f_64(arr[0]),
      y: dco_decode_f_64(arr[1]),
      z: dco_decode_f_64(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<Checkpoint> dco_decode_list_checkpoint(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_checkpoint).toList();
  }

  @protected
  List<GeoPoint> dco_decode_list_geo_point(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_geo_point).toList();
  }

  @protected
  List<Polygon> dco_decode_list_polygon(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_polygon).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Trajectory> dco_decode_list_trajectory(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_trajectory).toList();
  }

  @protected
  MovementPhase dco_decode_movement_phase(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MovementPhase.values[raw as int];
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  AccelerometerData? dco_decode_opt_box_autoadd_accelerometer_data(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_accelerometer_data(raw);
  }

  @protected
  BarometerData? dco_decode_opt_box_autoadd_barometer_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_barometer_data(raw);
  }

  @protected
  CompassData? dco_decode_opt_box_autoadd_compass_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_compass_data(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  GeoPoint? dco_decode_opt_box_autoadd_geo_point(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_geo_point(raw);
  }

  @protected
  GpsData? dco_decode_opt_box_autoadd_gps_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_gps_data(raw);
  }

  @protected
  GyroscopeData? dco_decode_opt_box_autoadd_gyroscope_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_gyroscope_data(raw);
  }

  @protected
  PedometerData? dco_decode_opt_box_autoadd_pedometer_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_pedometer_data(raw);
  }

  @protected
  Polygon? dco_decode_opt_box_autoadd_polygon(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_polygon(raw);
  }

  @protected
  SensorData? dco_decode_opt_box_autoadd_sensor_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_sensor_data(raw);
  }

  @protected
  SimulatorConfig? dco_decode_opt_box_autoadd_simulator_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_simulator_config(raw);
  }

  @protected
  SimulatorState? dco_decode_opt_box_autoadd_simulator_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_simulator_state(raw);
  }

  @protected
  SimulatorStats? dco_decode_opt_box_autoadd_simulator_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_simulator_stats(raw);
  }

  @protected
  PedometerData dco_decode_pedometer_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PedometerData(
      totalSteps: dco_decode_u_64(arr[0]),
      currentStepFrequency: dco_decode_f_64(arr[1]),
      currentStrideLength: dco_decode_f_64(arr[2]),
      distance: dco_decode_f_64(arr[3]),
    );
  }

  @protected
  Polygon dco_decode_polygon(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return Polygon(points: dco_decode_list_geo_point(arr[0]));
  }

  @protected
  SensorData dco_decode_sensor_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return SensorData(
      timestamp: dco_decode_i_64(arr[0]),
      gps: dco_decode_opt_box_autoadd_gps_data(arr[1]),
      accelerometer: dco_decode_opt_box_autoadd_accelerometer_data(arr[2]),
      gyroscope: dco_decode_opt_box_autoadd_gyroscope_data(arr[3]),
      compass: dco_decode_opt_box_autoadd_compass_data(arr[4]),
      barometer: dco_decode_opt_box_autoadd_barometer_data(arr[5]),
      pedometer: dco_decode_opt_box_autoadd_pedometer_data(arr[6]),
    );
  }

  @protected
  SimulatorConfig dco_decode_simulator_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 32)
      throw Exception('unexpected arr length: expect 32 but see ${arr.length}');
    return SimulatorConfig(
      targetSpeed: dco_decode_f_64(arr[0]),
      minSpeed: dco_decode_f_64(arr[1]),
      maxSpeed: dco_decode_f_64(arr[2]),
      acceleration: dco_decode_f_64(arr[3]),
      deceleration: dco_decode_f_64(arr[4]),
      stepFrequency: dco_decode_f_64(arr[5]),
      strideLength: dco_decode_f_64(arr[6]),
      gpsRefreshRate: dco_decode_f_64(arr[7]),
      accelerometerRefreshRate: dco_decode_f_64(arr[8]),
      gyroscopeRefreshRate: dco_decode_f_64(arr[9]),
      compassRefreshRate: dco_decode_f_64(arr[10]),
      barometerRefreshRate: dco_decode_f_64(arr[11]),
      jitterSeed: dco_decode_u_64(arr[12]),
      positionJitterAmplitude: dco_decode_f_64(arr[13]),
      speedJitterAmplitude: dco_decode_f_64(arr[14]),
      bearingJitterAmplitude: dco_decode_f_64(arr[15]),
      accelerometerJitterAmplitude: dco_decode_f_64(arr[16]),
      gyroscopeJitterAmplitude: dco_decode_f_64(arr[17]),
      jitterFrequencyScale: dco_decode_f_64(arr[18]),
      trajectoryMode: dco_decode_trajectory_mode(arr[19]),
      loopCount: dco_decode_u_32(arr[20]),
      geofence: dco_decode_opt_box_autoadd_polygon(arr[21]),
      forbiddenZones: dco_decode_list_polygon(arr[22]),
      fenceWarningDistance: dco_decode_f_64(arr[23]),
      checkpoints: dco_decode_list_checkpoint(arr[24]),
      checkpointTolerance: dco_decode_f_64(arr[25]),
      autoRouteToCheckpoint: dco_decode_bool(arr[26]),
      checkpointStayTime: dco_decode_f_64(arr[27]),
      pathfindingGridResolution: dco_decode_f_64(arr[28]),
      smoothingFactor: dco_decode_f_64(arr[29]),
      baseAltitude: dco_decode_f_64(arr[30]),
      altitudeVariation: dco_decode_f_64(arr[31]),
    );
  }

  @protected
  SimulatorEvent dco_decode_simulator_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return SimulatorEvent_Started();
      case 1:
        return SimulatorEvent_Paused();
      case 2:
        return SimulatorEvent_Resumed();
      case 3:
        return SimulatorEvent_Stopped(reason: dco_decode_stop_reason(raw[1]));
      case 4:
        return SimulatorEvent_SensorDataUpdated(
          data: dco_decode_box_autoadd_sensor_data(raw[1]),
        );
      case 5:
        return SimulatorEvent_PositionUpdated(
          position: dco_decode_box_autoadd_geo_point(raw[1]),
          speed: dco_decode_f_64(raw[2]),
          bearing: dco_decode_f_64(raw[3]),
        );
      case 6:
        return SimulatorEvent_SpeedChanged(
          oldSpeed: dco_decode_f_64(raw[1]),
          newSpeed: dco_decode_f_64(raw[2]),
        );
      case 7:
        return SimulatorEvent_PhaseChanged(
          oldPhase: dco_decode_movement_phase(raw[1]),
          newPhase: dco_decode_movement_phase(raw[2]),
        );
      case 8:
        return SimulatorEvent_TrajectorySwitched(
          index: dco_decode_usize(raw[1]),
          trajectoryId: dco_decode_String(raw[2]),
        );
      case 9:
        return SimulatorEvent_CheckpointReached(
          checkpoint: dco_decode_box_autoadd_checkpoint(raw[1]),
        );
      case 10:
        return SimulatorEvent_AllCheckpointsCompleted();
      case 11:
        return SimulatorEvent_GeofenceEntered();
      case 12:
        return SimulatorEvent_GeofenceExited();
      case 13:
        return SimulatorEvent_ForbiddenZoneEntered(
          zoneIndex: dco_decode_usize(raw[1]),
        );
      case 14:
        return SimulatorEvent_ForbiddenZoneExited(
          zoneIndex: dco_decode_usize(raw[1]),
        );
      case 15:
        return SimulatorEvent_ErrorOccurred(message: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  SimulatorState dco_decode_simulator_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SimulatorState.values[raw as int];
  }

  @protected
  SimulatorStats dco_decode_simulator_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return SimulatorStats(
      elapsedTimeMs: dco_decode_u_64(arr[0]),
      totalDistance: dco_decode_f_64(arr[1]),
      currentSpeed: dco_decode_f_64(arr[2]),
      averageSpeed: dco_decode_f_64(arr[3]),
      calories: dco_decode_f_64(arr[4]),
      totalSteps: dco_decode_u_64(arr[5]),
      currentTrajectoryIndex: dco_decode_usize(arr[6]),
      trajectoryProgress: dco_decode_f_64(arr[7]),
      checkedPoints: dco_decode_u_32(arr[8]),
      currentPhase: dco_decode_movement_phase(arr[9]),
      currentPosition: dco_decode_opt_box_autoadd_geo_point(arr[10]),
    );
  }

  @protected
  SimulatorUpdate dco_decode_simulator_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return SimulatorUpdate_Event(
          dco_decode_box_autoadd_simulator_event(raw[1]),
        );
      case 1:
        return SimulatorUpdate_SensorData(
          dco_decode_box_autoadd_sensor_data(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  StopReason dco_decode_stop_reason(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return StopReason.values[raw as int];
  }

  @protected
  Trajectory dco_decode_trajectory(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Trajectory(
      id: dco_decode_String(arr[0]),
      name: dco_decode_opt_String(arr[1]),
      points: dco_decode_list_geo_point(arr[2]),
    );
  }

  @protected
  TrajectoryMode dco_decode_trajectory_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TrajectoryMode.values[raw as int];
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<SimulatorUpdate> sse_decode_StreamSink_simulator_update_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AccelerometerData sse_decode_accelerometer_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_x = sse_decode_f_64(deserializer);
    var var_y = sse_decode_f_64(deserializer);
    var var_z = sse_decode_f_64(deserializer);
    return AccelerometerData(x: var_x, y: var_y, z: var_z);
  }

  @protected
  BarometerData sse_decode_barometer_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pressure = sse_decode_f_64(deserializer);
    var var_relativeAltitude = sse_decode_f_64(deserializer);
    return BarometerData(
      pressure: var_pressure,
      relativeAltitude: var_relativeAltitude,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AccelerometerData sse_decode_box_autoadd_accelerometer_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_accelerometer_data(deserializer));
  }

  @protected
  BarometerData sse_decode_box_autoadd_barometer_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_barometer_data(deserializer));
  }

  @protected
  Checkpoint sse_decode_box_autoadd_checkpoint(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_checkpoint(deserializer));
  }

  @protected
  Command sse_decode_box_autoadd_command(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_command(deserializer));
  }

  @protected
  CompassData sse_decode_box_autoadd_compass_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_compass_data(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  GeoPoint sse_decode_box_autoadd_geo_point(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_geo_point(deserializer));
  }

  @protected
  GpsData sse_decode_box_autoadd_gps_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_gps_data(deserializer));
  }

  @protected
  GyroscopeData sse_decode_box_autoadd_gyroscope_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_gyroscope_data(deserializer));
  }

  @protected
  PedometerData sse_decode_box_autoadd_pedometer_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_pedometer_data(deserializer));
  }

  @protected
  Polygon sse_decode_box_autoadd_polygon(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_polygon(deserializer));
  }

  @protected
  SensorData sse_decode_box_autoadd_sensor_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_sensor_data(deserializer));
  }

  @protected
  SimulatorConfig sse_decode_box_autoadd_simulator_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_simulator_config(deserializer));
  }

  @protected
  SimulatorEvent sse_decode_box_autoadd_simulator_event(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_simulator_event(deserializer));
  }

  @protected
  SimulatorState sse_decode_box_autoadd_simulator_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_simulator_state(deserializer));
  }

  @protected
  SimulatorStats sse_decode_box_autoadd_simulator_stats(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_simulator_stats(deserializer));
  }

  @protected
  Trajectory sse_decode_box_autoadd_trajectory(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_trajectory(deserializer));
  }

  @protected
  Checkpoint sse_decode_checkpoint(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_opt_String(deserializer);
    var var_point = sse_decode_opt_box_autoadd_geo_point(deserializer);
    var var_area = sse_decode_opt_box_autoadd_polygon(deserializer);
    var var_radius = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_mandatory = sse_decode_bool(deserializer);
    var var_sequence = sse_decode_u_32(deserializer);
    var var_checked = sse_decode_bool(deserializer);
    return Checkpoint(
      id: var_id,
      name: var_name,
      point: var_point,
      area: var_area,
      radius: var_radius,
      mandatory: var_mandatory,
      sequence: var_sequence,
      checked: var_checked,
    );
  }

  @protected
  Command sse_decode_command(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_f_64(deserializer);
        return Command_SetTargetSpeed(var_field0);
      case 1:
        var var_min = sse_decode_f_64(deserializer);
        var var_max = sse_decode_f_64(deserializer);
        return Command_SetSpeedRange(min: var_min, max: var_max);
      case 2:
        var var_field0 = sse_decode_f_64(deserializer);
        return Command_SetAcceleration(var_field0);
      case 3:
        var var_field0 = sse_decode_f_64(deserializer);
        return Command_SetDeceleration(var_field0);
      case 4:
        var var_field0 = sse_decode_f_64(deserializer);
        return Command_SetStepFrequency(var_field0);
      case 5:
        var var_field0 = sse_decode_f_64(deserializer);
        return Command_SetStrideLength(var_field0);
      case 6:
        return Command_Pause();
      case 7:
        return Command_Resume();
      case 8:
        return Command_StopImmediately();
      case 9:
        var var_frames = sse_decode_u_32(deserializer);
        var var_graceful = sse_decode_bool(deserializer);
        return Command_StopAfterFrames(
          frames: var_frames,
          graceful: var_graceful,
        );
      case 10:
        var var_seconds = sse_decode_f_64(deserializer);
        var var_graceful = sse_decode_bool(deserializer);
        return Command_StopAfterTime(
          seconds: var_seconds,
          graceful: var_graceful,
        );
      case 11:
        var var_field0 = sse_decode_f_64(deserializer);
        return Command_JumpToProgress(var_field0);
      case 12:
        return Command_NextTrajectory();
      case 13:
        var var_field0 = sse_decode_box_autoadd_checkpoint(deserializer);
        return Command_AddCheckpoint(var_field0);
      case 14:
        var var_field0 = sse_decode_String(deserializer);
        return Command_RemoveCheckpoint(var_field0);
      case 15:
        return Command_ClearCheckpoints();
      case 16:
        return Command_ResetCheckpointStatus();
      case 17:
        var var_positionAmplitude = sse_decode_opt_box_autoadd_f_64(
          deserializer,
        );
        var var_speedAmplitude = sse_decode_opt_box_autoadd_f_64(deserializer);
        var var_bearingAmplitude = sse_decode_opt_box_autoadd_f_64(
          deserializer,
        );
        return Command_SetJitterParams(
          positionAmplitude: var_positionAmplitude,
          speedAmplitude: var_speedAmplitude,
          bearingAmplitude: var_bearingAmplitude,
        );
      case 18:
        var var_gps = sse_decode_opt_box_autoadd_f_64(deserializer);
        var var_accelerometer = sse_decode_opt_box_autoadd_f_64(deserializer);
        var var_gyroscope = sse_decode_opt_box_autoadd_f_64(deserializer);
        var var_compass = sse_decode_opt_box_autoadd_f_64(deserializer);
        var var_barometer = sse_decode_opt_box_autoadd_f_64(deserializer);
        return Command_SetRefreshRate(
          gps: var_gps,
          accelerometer: var_accelerometer,
          gyroscope: var_gyroscope,
          compass: var_compass,
          barometer: var_barometer,
        );
      case 19:
        var var_field0 = sse_decode_f_64(deserializer);
        return Command_SetFenceWarningDistance(var_field0);
      case 20:
        var var_index = sse_decode_usize(deserializer);
        var var_seamless = sse_decode_bool(deserializer);
        return Command_SwitchTrajectory(
          index: var_index,
          seamless: var_seamless,
        );
      case 21:
        var var_field0 = sse_decode_box_autoadd_trajectory(deserializer);
        return Command_AppendTrajectory(var_field0);
      case 22:
        var var_field0 = sse_decode_String(deserializer);
        return Command_Custom(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  CommandResult sse_decode_command_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_data = sse_decode_opt_String(deserializer);
    return CommandResult(
      success: var_success,
      message: var_message,
      data: var_data,
    );
  }

  @protected
  CompassData sse_decode_compass_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_magneticHeading = sse_decode_f_64(deserializer);
    var var_trueHeading = sse_decode_f_64(deserializer);
    var var_declination = sse_decode_f_64(deserializer);
    var var_magneticFieldX = sse_decode_f_64(deserializer);
    var var_magneticFieldY = sse_decode_f_64(deserializer);
    var var_magneticFieldZ = sse_decode_f_64(deserializer);
    return CompassData(
      magneticHeading: var_magneticHeading,
      trueHeading: var_trueHeading,
      declination: var_declination,
      magneticFieldX: var_magneticFieldX,
      magneticFieldY: var_magneticFieldY,
      magneticFieldZ: var_magneticFieldZ,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  GeoPoint sse_decode_geo_point(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_latitude = sse_decode_f_64(deserializer);
    var var_longitude = sse_decode_f_64(deserializer);
    var var_altitude = sse_decode_opt_box_autoadd_f_64(deserializer);
    return GeoPoint(
      latitude: var_latitude,
      longitude: var_longitude,
      altitude: var_altitude,
    );
  }

  @protected
  GpsData sse_decode_gps_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_position = sse_decode_geo_point(deserializer);
    var var_speed = sse_decode_f_64(deserializer);
    var var_bearing = sse_decode_f_64(deserializer);
    var var_horizontalAccuracy = sse_decode_f_64(deserializer);
    var var_verticalAccuracy = sse_decode_f_64(deserializer);
    var var_satelliteCount = sse_decode_u_8(deserializer);
    return GpsData(
      position: var_position,
      speed: var_speed,
      bearing: var_bearing,
      horizontalAccuracy: var_horizontalAccuracy,
      verticalAccuracy: var_verticalAccuracy,
      satelliteCount: var_satelliteCount,
    );
  }

  @protected
  GyroscopeData sse_decode_gyroscope_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_x = sse_decode_f_64(deserializer);
    var var_y = sse_decode_f_64(deserializer);
    var var_z = sse_decode_f_64(deserializer);
    return GyroscopeData(x: var_x, y: var_y, z: var_z);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<Checkpoint> sse_decode_list_checkpoint(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Checkpoint>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_checkpoint(deserializer));
    }
    return ans_;
  }

  @protected
  List<GeoPoint> sse_decode_list_geo_point(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <GeoPoint>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_geo_point(deserializer));
    }
    return ans_;
  }

  @protected
  List<Polygon> sse_decode_list_polygon(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Polygon>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_polygon(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Trajectory> sse_decode_list_trajectory(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Trajectory>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_trajectory(deserializer));
    }
    return ans_;
  }

  @protected
  MovementPhase sse_decode_movement_phase(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MovementPhase.values[inner];
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  AccelerometerData? sse_decode_opt_box_autoadd_accelerometer_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_accelerometer_data(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BarometerData? sse_decode_opt_box_autoadd_barometer_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_barometer_data(deserializer));
    } else {
      return null;
    }
  }

  @protected
  CompassData? sse_decode_opt_box_autoadd_compass_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_compass_data(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  GeoPoint? sse_decode_opt_box_autoadd_geo_point(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_geo_point(deserializer));
    } else {
      return null;
    }
  }

  @protected
  GpsData? sse_decode_opt_box_autoadd_gps_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_gps_data(deserializer));
    } else {
      return null;
    }
  }

  @protected
  GyroscopeData? sse_decode_opt_box_autoadd_gyroscope_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_gyroscope_data(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PedometerData? sse_decode_opt_box_autoadd_pedometer_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_pedometer_data(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Polygon? sse_decode_opt_box_autoadd_polygon(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_polygon(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SensorData? sse_decode_opt_box_autoadd_sensor_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_sensor_data(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SimulatorConfig? sse_decode_opt_box_autoadd_simulator_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_simulator_config(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SimulatorState? sse_decode_opt_box_autoadd_simulator_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_simulator_state(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SimulatorStats? sse_decode_opt_box_autoadd_simulator_stats(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_simulator_stats(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PedometerData sse_decode_pedometer_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_totalSteps = sse_decode_u_64(deserializer);
    var var_currentStepFrequency = sse_decode_f_64(deserializer);
    var var_currentStrideLength = sse_decode_f_64(deserializer);
    var var_distance = sse_decode_f_64(deserializer);
    return PedometerData(
      totalSteps: var_totalSteps,
      currentStepFrequency: var_currentStepFrequency,
      currentStrideLength: var_currentStrideLength,
      distance: var_distance,
    );
  }

  @protected
  Polygon sse_decode_polygon(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_points = sse_decode_list_geo_point(deserializer);
    return Polygon(points: var_points);
  }

  @protected
  SensorData sse_decode_sensor_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timestamp = sse_decode_i_64(deserializer);
    var var_gps = sse_decode_opt_box_autoadd_gps_data(deserializer);
    var var_accelerometer = sse_decode_opt_box_autoadd_accelerometer_data(
      deserializer,
    );
    var var_gyroscope = sse_decode_opt_box_autoadd_gyroscope_data(deserializer);
    var var_compass = sse_decode_opt_box_autoadd_compass_data(deserializer);
    var var_barometer = sse_decode_opt_box_autoadd_barometer_data(deserializer);
    var var_pedometer = sse_decode_opt_box_autoadd_pedometer_data(deserializer);
    return SensorData(
      timestamp: var_timestamp,
      gps: var_gps,
      accelerometer: var_accelerometer,
      gyroscope: var_gyroscope,
      compass: var_compass,
      barometer: var_barometer,
      pedometer: var_pedometer,
    );
  }

  @protected
  SimulatorConfig sse_decode_simulator_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_targetSpeed = sse_decode_f_64(deserializer);
    var var_minSpeed = sse_decode_f_64(deserializer);
    var var_maxSpeed = sse_decode_f_64(deserializer);
    var var_acceleration = sse_decode_f_64(deserializer);
    var var_deceleration = sse_decode_f_64(deserializer);
    var var_stepFrequency = sse_decode_f_64(deserializer);
    var var_strideLength = sse_decode_f_64(deserializer);
    var var_gpsRefreshRate = sse_decode_f_64(deserializer);
    var var_accelerometerRefreshRate = sse_decode_f_64(deserializer);
    var var_gyroscopeRefreshRate = sse_decode_f_64(deserializer);
    var var_compassRefreshRate = sse_decode_f_64(deserializer);
    var var_barometerRefreshRate = sse_decode_f_64(deserializer);
    var var_jitterSeed = sse_decode_u_64(deserializer);
    var var_positionJitterAmplitude = sse_decode_f_64(deserializer);
    var var_speedJitterAmplitude = sse_decode_f_64(deserializer);
    var var_bearingJitterAmplitude = sse_decode_f_64(deserializer);
    var var_accelerometerJitterAmplitude = sse_decode_f_64(deserializer);
    var var_gyroscopeJitterAmplitude = sse_decode_f_64(deserializer);
    var var_jitterFrequencyScale = sse_decode_f_64(deserializer);
    var var_trajectoryMode = sse_decode_trajectory_mode(deserializer);
    var var_loopCount = sse_decode_u_32(deserializer);
    var var_geofence = sse_decode_opt_box_autoadd_polygon(deserializer);
    var var_forbiddenZones = sse_decode_list_polygon(deserializer);
    var var_fenceWarningDistance = sse_decode_f_64(deserializer);
    var var_checkpoints = sse_decode_list_checkpoint(deserializer);
    var var_checkpointTolerance = sse_decode_f_64(deserializer);
    var var_autoRouteToCheckpoint = sse_decode_bool(deserializer);
    var var_checkpointStayTime = sse_decode_f_64(deserializer);
    var var_pathfindingGridResolution = sse_decode_f_64(deserializer);
    var var_smoothingFactor = sse_decode_f_64(deserializer);
    var var_baseAltitude = sse_decode_f_64(deserializer);
    var var_altitudeVariation = sse_decode_f_64(deserializer);
    return SimulatorConfig(
      targetSpeed: var_targetSpeed,
      minSpeed: var_minSpeed,
      maxSpeed: var_maxSpeed,
      acceleration: var_acceleration,
      deceleration: var_deceleration,
      stepFrequency: var_stepFrequency,
      strideLength: var_strideLength,
      gpsRefreshRate: var_gpsRefreshRate,
      accelerometerRefreshRate: var_accelerometerRefreshRate,
      gyroscopeRefreshRate: var_gyroscopeRefreshRate,
      compassRefreshRate: var_compassRefreshRate,
      barometerRefreshRate: var_barometerRefreshRate,
      jitterSeed: var_jitterSeed,
      positionJitterAmplitude: var_positionJitterAmplitude,
      speedJitterAmplitude: var_speedJitterAmplitude,
      bearingJitterAmplitude: var_bearingJitterAmplitude,
      accelerometerJitterAmplitude: var_accelerometerJitterAmplitude,
      gyroscopeJitterAmplitude: var_gyroscopeJitterAmplitude,
      jitterFrequencyScale: var_jitterFrequencyScale,
      trajectoryMode: var_trajectoryMode,
      loopCount: var_loopCount,
      geofence: var_geofence,
      forbiddenZones: var_forbiddenZones,
      fenceWarningDistance: var_fenceWarningDistance,
      checkpoints: var_checkpoints,
      checkpointTolerance: var_checkpointTolerance,
      autoRouteToCheckpoint: var_autoRouteToCheckpoint,
      checkpointStayTime: var_checkpointStayTime,
      pathfindingGridResolution: var_pathfindingGridResolution,
      smoothingFactor: var_smoothingFactor,
      baseAltitude: var_baseAltitude,
      altitudeVariation: var_altitudeVariation,
    );
  }

  @protected
  SimulatorEvent sse_decode_simulator_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return SimulatorEvent_Started();
      case 1:
        return SimulatorEvent_Paused();
      case 2:
        return SimulatorEvent_Resumed();
      case 3:
        var var_reason = sse_decode_stop_reason(deserializer);
        return SimulatorEvent_Stopped(reason: var_reason);
      case 4:
        var var_data = sse_decode_box_autoadd_sensor_data(deserializer);
        return SimulatorEvent_SensorDataUpdated(data: var_data);
      case 5:
        var var_position = sse_decode_box_autoadd_geo_point(deserializer);
        var var_speed = sse_decode_f_64(deserializer);
        var var_bearing = sse_decode_f_64(deserializer);
        return SimulatorEvent_PositionUpdated(
          position: var_position,
          speed: var_speed,
          bearing: var_bearing,
        );
      case 6:
        var var_oldSpeed = sse_decode_f_64(deserializer);
        var var_newSpeed = sse_decode_f_64(deserializer);
        return SimulatorEvent_SpeedChanged(
          oldSpeed: var_oldSpeed,
          newSpeed: var_newSpeed,
        );
      case 7:
        var var_oldPhase = sse_decode_movement_phase(deserializer);
        var var_newPhase = sse_decode_movement_phase(deserializer);
        return SimulatorEvent_PhaseChanged(
          oldPhase: var_oldPhase,
          newPhase: var_newPhase,
        );
      case 8:
        var var_index = sse_decode_usize(deserializer);
        var var_trajectoryId = sse_decode_String(deserializer);
        return SimulatorEvent_TrajectorySwitched(
          index: var_index,
          trajectoryId: var_trajectoryId,
        );
      case 9:
        var var_checkpoint = sse_decode_box_autoadd_checkpoint(deserializer);
        return SimulatorEvent_CheckpointReached(checkpoint: var_checkpoint);
      case 10:
        return SimulatorEvent_AllCheckpointsCompleted();
      case 11:
        return SimulatorEvent_GeofenceEntered();
      case 12:
        return SimulatorEvent_GeofenceExited();
      case 13:
        var var_zoneIndex = sse_decode_usize(deserializer);
        return SimulatorEvent_ForbiddenZoneEntered(zoneIndex: var_zoneIndex);
      case 14:
        var var_zoneIndex = sse_decode_usize(deserializer);
        return SimulatorEvent_ForbiddenZoneExited(zoneIndex: var_zoneIndex);
      case 15:
        var var_message = sse_decode_String(deserializer);
        return SimulatorEvent_ErrorOccurred(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  SimulatorState sse_decode_simulator_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SimulatorState.values[inner];
  }

  @protected
  SimulatorStats sse_decode_simulator_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_elapsedTimeMs = sse_decode_u_64(deserializer);
    var var_totalDistance = sse_decode_f_64(deserializer);
    var var_currentSpeed = sse_decode_f_64(deserializer);
    var var_averageSpeed = sse_decode_f_64(deserializer);
    var var_calories = sse_decode_f_64(deserializer);
    var var_totalSteps = sse_decode_u_64(deserializer);
    var var_currentTrajectoryIndex = sse_decode_usize(deserializer);
    var var_trajectoryProgress = sse_decode_f_64(deserializer);
    var var_checkedPoints = sse_decode_u_32(deserializer);
    var var_currentPhase = sse_decode_movement_phase(deserializer);
    var var_currentPosition = sse_decode_opt_box_autoadd_geo_point(
      deserializer,
    );
    return SimulatorStats(
      elapsedTimeMs: var_elapsedTimeMs,
      totalDistance: var_totalDistance,
      currentSpeed: var_currentSpeed,
      averageSpeed: var_averageSpeed,
      calories: var_calories,
      totalSteps: var_totalSteps,
      currentTrajectoryIndex: var_currentTrajectoryIndex,
      trajectoryProgress: var_trajectoryProgress,
      checkedPoints: var_checkedPoints,
      currentPhase: var_currentPhase,
      currentPosition: var_currentPosition,
    );
  }

  @protected
  SimulatorUpdate sse_decode_simulator_update(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_box_autoadd_simulator_event(deserializer);
        return SimulatorUpdate_Event(var_field0);
      case 1:
        var var_field0 = sse_decode_box_autoadd_sensor_data(deserializer);
        return SimulatorUpdate_SensorData(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  StopReason sse_decode_stop_reason(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return StopReason.values[inner];
  }

  @protected
  Trajectory sse_decode_trajectory(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_opt_String(deserializer);
    var var_points = sse_decode_list_geo_point(deserializer);
    return Trajectory(id: var_id, name: var_name, points: var_points);
  }

  @protected
  TrajectoryMode sse_decode_trajectory_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TrajectoryMode.values[inner];
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_simulator_update_Sse(
    RustStreamSink<SimulatorUpdate> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_simulator_update,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_accelerometer_data(
    AccelerometerData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.x, serializer);
    sse_encode_f_64(self.y, serializer);
    sse_encode_f_64(self.z, serializer);
  }

  @protected
  void sse_encode_barometer_data(BarometerData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.pressure, serializer);
    sse_encode_f_64(self.relativeAltitude, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_accelerometer_data(
    AccelerometerData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_accelerometer_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_barometer_data(
    BarometerData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_barometer_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_checkpoint(
    Checkpoint self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_checkpoint(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_command(Command self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_command(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_compass_data(
    CompassData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_compass_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_geo_point(
    GeoPoint self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_geo_point(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_gps_data(GpsData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_gps_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_gyroscope_data(
    GyroscopeData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_gyroscope_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_pedometer_data(
    PedometerData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_pedometer_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_polygon(Polygon self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_polygon(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_sensor_data(
    SensorData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_sensor_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_simulator_config(
    SimulatorConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_simulator_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_simulator_event(
    SimulatorEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_simulator_event(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_simulator_state(
    SimulatorState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_simulator_state(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_simulator_stats(
    SimulatorStats self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_simulator_stats(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_trajectory(
    Trajectory self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_trajectory(self, serializer);
  }

  @protected
  void sse_encode_checkpoint(Checkpoint self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_opt_String(self.name, serializer);
    sse_encode_opt_box_autoadd_geo_point(self.point, serializer);
    sse_encode_opt_box_autoadd_polygon(self.area, serializer);
    sse_encode_opt_box_autoadd_f_64(self.radius, serializer);
    sse_encode_bool(self.mandatory, serializer);
    sse_encode_u_32(self.sequence, serializer);
    sse_encode_bool(self.checked, serializer);
  }

  @protected
  void sse_encode_command(Command self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case Command_SetTargetSpeed(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_f_64(field0, serializer);
      case Command_SetSpeedRange(min: final min, max: final max):
        sse_encode_i_32(1, serializer);
        sse_encode_f_64(min, serializer);
        sse_encode_f_64(max, serializer);
      case Command_SetAcceleration(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_f_64(field0, serializer);
      case Command_SetDeceleration(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_f_64(field0, serializer);
      case Command_SetStepFrequency(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_f_64(field0, serializer);
      case Command_SetStrideLength(field0: final field0):
        sse_encode_i_32(5, serializer);
        sse_encode_f_64(field0, serializer);
      case Command_Pause():
        sse_encode_i_32(6, serializer);
      case Command_Resume():
        sse_encode_i_32(7, serializer);
      case Command_StopImmediately():
        sse_encode_i_32(8, serializer);
      case Command_StopAfterFrames(
        frames: final frames,
        graceful: final graceful,
      ):
        sse_encode_i_32(9, serializer);
        sse_encode_u_32(frames, serializer);
        sse_encode_bool(graceful, serializer);
      case Command_StopAfterTime(
        seconds: final seconds,
        graceful: final graceful,
      ):
        sse_encode_i_32(10, serializer);
        sse_encode_f_64(seconds, serializer);
        sse_encode_bool(graceful, serializer);
      case Command_JumpToProgress(field0: final field0):
        sse_encode_i_32(11, serializer);
        sse_encode_f_64(field0, serializer);
      case Command_NextTrajectory():
        sse_encode_i_32(12, serializer);
      case Command_AddCheckpoint(field0: final field0):
        sse_encode_i_32(13, serializer);
        sse_encode_box_autoadd_checkpoint(field0, serializer);
      case Command_RemoveCheckpoint(field0: final field0):
        sse_encode_i_32(14, serializer);
        sse_encode_String(field0, serializer);
      case Command_ClearCheckpoints():
        sse_encode_i_32(15, serializer);
      case Command_ResetCheckpointStatus():
        sse_encode_i_32(16, serializer);
      case Command_SetJitterParams(
        positionAmplitude: final positionAmplitude,
        speedAmplitude: final speedAmplitude,
        bearingAmplitude: final bearingAmplitude,
      ):
        sse_encode_i_32(17, serializer);
        sse_encode_opt_box_autoadd_f_64(positionAmplitude, serializer);
        sse_encode_opt_box_autoadd_f_64(speedAmplitude, serializer);
        sse_encode_opt_box_autoadd_f_64(bearingAmplitude, serializer);
      case Command_SetRefreshRate(
        gps: final gps,
        accelerometer: final accelerometer,
        gyroscope: final gyroscope,
        compass: final compass,
        barometer: final barometer,
      ):
        sse_encode_i_32(18, serializer);
        sse_encode_opt_box_autoadd_f_64(gps, serializer);
        sse_encode_opt_box_autoadd_f_64(accelerometer, serializer);
        sse_encode_opt_box_autoadd_f_64(gyroscope, serializer);
        sse_encode_opt_box_autoadd_f_64(compass, serializer);
        sse_encode_opt_box_autoadd_f_64(barometer, serializer);
      case Command_SetFenceWarningDistance(field0: final field0):
        sse_encode_i_32(19, serializer);
        sse_encode_f_64(field0, serializer);
      case Command_SwitchTrajectory(
        index: final index,
        seamless: final seamless,
      ):
        sse_encode_i_32(20, serializer);
        sse_encode_usize(index, serializer);
        sse_encode_bool(seamless, serializer);
      case Command_AppendTrajectory(field0: final field0):
        sse_encode_i_32(21, serializer);
        sse_encode_box_autoadd_trajectory(field0, serializer);
      case Command_Custom(field0: final field0):
        sse_encode_i_32(22, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_command_result(CommandResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_opt_String(self.data, serializer);
  }

  @protected
  void sse_encode_compass_data(CompassData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.magneticHeading, serializer);
    sse_encode_f_64(self.trueHeading, serializer);
    sse_encode_f_64(self.declination, serializer);
    sse_encode_f_64(self.magneticFieldX, serializer);
    sse_encode_f_64(self.magneticFieldY, serializer);
    sse_encode_f_64(self.magneticFieldZ, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_geo_point(GeoPoint self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.latitude, serializer);
    sse_encode_f_64(self.longitude, serializer);
    sse_encode_opt_box_autoadd_f_64(self.altitude, serializer);
  }

  @protected
  void sse_encode_gps_data(GpsData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_geo_point(self.position, serializer);
    sse_encode_f_64(self.speed, serializer);
    sse_encode_f_64(self.bearing, serializer);
    sse_encode_f_64(self.horizontalAccuracy, serializer);
    sse_encode_f_64(self.verticalAccuracy, serializer);
    sse_encode_u_8(self.satelliteCount, serializer);
  }

  @protected
  void sse_encode_gyroscope_data(GyroscopeData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.x, serializer);
    sse_encode_f_64(self.y, serializer);
    sse_encode_f_64(self.z, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_checkpoint(
    List<Checkpoint> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_checkpoint(item, serializer);
    }
  }

  @protected
  void sse_encode_list_geo_point(
    List<GeoPoint> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_geo_point(item, serializer);
    }
  }

  @protected
  void sse_encode_list_polygon(List<Polygon> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_polygon(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_trajectory(
    List<Trajectory> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_trajectory(item, serializer);
    }
  }

  @protected
  void sse_encode_movement_phase(MovementPhase self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_accelerometer_data(
    AccelerometerData? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_accelerometer_data(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_barometer_data(
    BarometerData? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_barometer_data(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_compass_data(
    CompassData? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_compass_data(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_geo_point(
    GeoPoint? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_geo_point(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_gps_data(
    GpsData? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_gps_data(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_gyroscope_data(
    GyroscopeData? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_gyroscope_data(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_pedometer_data(
    PedometerData? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_pedometer_data(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_polygon(
    Polygon? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_polygon(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_sensor_data(
    SensorData? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_sensor_data(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_simulator_config(
    SimulatorConfig? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_simulator_config(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_simulator_state(
    SimulatorState? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_simulator_state(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_simulator_stats(
    SimulatorStats? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_simulator_stats(self, serializer);
    }
  }

  @protected
  void sse_encode_pedometer_data(PedometerData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.totalSteps, serializer);
    sse_encode_f_64(self.currentStepFrequency, serializer);
    sse_encode_f_64(self.currentStrideLength, serializer);
    sse_encode_f_64(self.distance, serializer);
  }

  @protected
  void sse_encode_polygon(Polygon self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_geo_point(self.points, serializer);
  }

  @protected
  void sse_encode_sensor_data(SensorData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.timestamp, serializer);
    sse_encode_opt_box_autoadd_gps_data(self.gps, serializer);
    sse_encode_opt_box_autoadd_accelerometer_data(
      self.accelerometer,
      serializer,
    );
    sse_encode_opt_box_autoadd_gyroscope_data(self.gyroscope, serializer);
    sse_encode_opt_box_autoadd_compass_data(self.compass, serializer);
    sse_encode_opt_box_autoadd_barometer_data(self.barometer, serializer);
    sse_encode_opt_box_autoadd_pedometer_data(self.pedometer, serializer);
  }

  @protected
  void sse_encode_simulator_config(
    SimulatorConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.targetSpeed, serializer);
    sse_encode_f_64(self.minSpeed, serializer);
    sse_encode_f_64(self.maxSpeed, serializer);
    sse_encode_f_64(self.acceleration, serializer);
    sse_encode_f_64(self.deceleration, serializer);
    sse_encode_f_64(self.stepFrequency, serializer);
    sse_encode_f_64(self.strideLength, serializer);
    sse_encode_f_64(self.gpsRefreshRate, serializer);
    sse_encode_f_64(self.accelerometerRefreshRate, serializer);
    sse_encode_f_64(self.gyroscopeRefreshRate, serializer);
    sse_encode_f_64(self.compassRefreshRate, serializer);
    sse_encode_f_64(self.barometerRefreshRate, serializer);
    sse_encode_u_64(self.jitterSeed, serializer);
    sse_encode_f_64(self.positionJitterAmplitude, serializer);
    sse_encode_f_64(self.speedJitterAmplitude, serializer);
    sse_encode_f_64(self.bearingJitterAmplitude, serializer);
    sse_encode_f_64(self.accelerometerJitterAmplitude, serializer);
    sse_encode_f_64(self.gyroscopeJitterAmplitude, serializer);
    sse_encode_f_64(self.jitterFrequencyScale, serializer);
    sse_encode_trajectory_mode(self.trajectoryMode, serializer);
    sse_encode_u_32(self.loopCount, serializer);
    sse_encode_opt_box_autoadd_polygon(self.geofence, serializer);
    sse_encode_list_polygon(self.forbiddenZones, serializer);
    sse_encode_f_64(self.fenceWarningDistance, serializer);
    sse_encode_list_checkpoint(self.checkpoints, serializer);
    sse_encode_f_64(self.checkpointTolerance, serializer);
    sse_encode_bool(self.autoRouteToCheckpoint, serializer);
    sse_encode_f_64(self.checkpointStayTime, serializer);
    sse_encode_f_64(self.pathfindingGridResolution, serializer);
    sse_encode_f_64(self.smoothingFactor, serializer);
    sse_encode_f_64(self.baseAltitude, serializer);
    sse_encode_f_64(self.altitudeVariation, serializer);
  }

  @protected
  void sse_encode_simulator_event(
    SimulatorEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case SimulatorEvent_Started():
        sse_encode_i_32(0, serializer);
      case SimulatorEvent_Paused():
        sse_encode_i_32(1, serializer);
      case SimulatorEvent_Resumed():
        sse_encode_i_32(2, serializer);
      case SimulatorEvent_Stopped(reason: final reason):
        sse_encode_i_32(3, serializer);
        sse_encode_stop_reason(reason, serializer);
      case SimulatorEvent_SensorDataUpdated(data: final data):
        sse_encode_i_32(4, serializer);
        sse_encode_box_autoadd_sensor_data(data, serializer);
      case SimulatorEvent_PositionUpdated(
        position: final position,
        speed: final speed,
        bearing: final bearing,
      ):
        sse_encode_i_32(5, serializer);
        sse_encode_box_autoadd_geo_point(position, serializer);
        sse_encode_f_64(speed, serializer);
        sse_encode_f_64(bearing, serializer);
      case SimulatorEvent_SpeedChanged(
        oldSpeed: final oldSpeed,
        newSpeed: final newSpeed,
      ):
        sse_encode_i_32(6, serializer);
        sse_encode_f_64(oldSpeed, serializer);
        sse_encode_f_64(newSpeed, serializer);
      case SimulatorEvent_PhaseChanged(
        oldPhase: final oldPhase,
        newPhase: final newPhase,
      ):
        sse_encode_i_32(7, serializer);
        sse_encode_movement_phase(oldPhase, serializer);
        sse_encode_movement_phase(newPhase, serializer);
      case SimulatorEvent_TrajectorySwitched(
        index: final index,
        trajectoryId: final trajectoryId,
      ):
        sse_encode_i_32(8, serializer);
        sse_encode_usize(index, serializer);
        sse_encode_String(trajectoryId, serializer);
      case SimulatorEvent_CheckpointReached(checkpoint: final checkpoint):
        sse_encode_i_32(9, serializer);
        sse_encode_box_autoadd_checkpoint(checkpoint, serializer);
      case SimulatorEvent_AllCheckpointsCompleted():
        sse_encode_i_32(10, serializer);
      case SimulatorEvent_GeofenceEntered():
        sse_encode_i_32(11, serializer);
      case SimulatorEvent_GeofenceExited():
        sse_encode_i_32(12, serializer);
      case SimulatorEvent_ForbiddenZoneEntered(zoneIndex: final zoneIndex):
        sse_encode_i_32(13, serializer);
        sse_encode_usize(zoneIndex, serializer);
      case SimulatorEvent_ForbiddenZoneExited(zoneIndex: final zoneIndex):
        sse_encode_i_32(14, serializer);
        sse_encode_usize(zoneIndex, serializer);
      case SimulatorEvent_ErrorOccurred(message: final message):
        sse_encode_i_32(15, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_simulator_state(
    SimulatorState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_simulator_stats(
    SimulatorStats self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.elapsedTimeMs, serializer);
    sse_encode_f_64(self.totalDistance, serializer);
    sse_encode_f_64(self.currentSpeed, serializer);
    sse_encode_f_64(self.averageSpeed, serializer);
    sse_encode_f_64(self.calories, serializer);
    sse_encode_u_64(self.totalSteps, serializer);
    sse_encode_usize(self.currentTrajectoryIndex, serializer);
    sse_encode_f_64(self.trajectoryProgress, serializer);
    sse_encode_u_32(self.checkedPoints, serializer);
    sse_encode_movement_phase(self.currentPhase, serializer);
    sse_encode_opt_box_autoadd_geo_point(self.currentPosition, serializer);
  }

  @protected
  void sse_encode_simulator_update(
    SimulatorUpdate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case SimulatorUpdate_Event(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_simulator_event(field0, serializer);
      case SimulatorUpdate_SensorData(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_box_autoadd_sensor_data(field0, serializer);
    }
  }

  @protected
  void sse_encode_stop_reason(StopReason self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_trajectory(Trajectory self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_opt_String(self.name, serializer);
    sse_encode_list_geo_point(self.points, serializer);
  }

  @protected
  void sse_encode_trajectory_mode(
    TrajectoryMode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}
