// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'model.freezed.dart';

/// 加速度计数据
class AccelerometerData {
  /// X轴加速度（m/s²）
  final double x;

  /// Y轴加速度（m/s²）
  final double y;

  /// Z轴加速度（m/s²）
  final double z;

  const AccelerometerData({required this.x, required this.y, required this.z});

  @override
  int get hashCode => x.hashCode ^ y.hashCode ^ z.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccelerometerData &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          z == other.z;
}

/// 气压计数据
class BarometerData {
  /// 气压（百帕）
  final double pressure;

  /// 相对海拔（米）
  final double relativeAltitude;

  const BarometerData({required this.pressure, required this.relativeAltitude});

  @override
  int get hashCode => pressure.hashCode ^ relativeAltitude.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BarometerData &&
          runtimeType == other.runtimeType &&
          pressure == other.pressure &&
          relativeAltitude == other.relativeAltitude;
}

/// 打卡点
class Checkpoint {
  /// 打卡点ID
  final String id;

  /// 打卡点名称
  final String? name;

  /// 打卡点位置（点打卡）
  final GeoPoint? point;

  /// 打卡区域（区域打卡）
  final Polygon? area;

  /// 打卡半径（米），用于点打卡
  final double? radius;

  /// 是否必经
  final bool mandatory;

  /// 顺序编号
  final int sequence;

  /// 是否已打卡
  final bool checked;

  const Checkpoint({
    required this.id,
    this.name,
    this.point,
    this.area,
    this.radius,
    required this.mandatory,
    required this.sequence,
    required this.checked,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      point.hashCode ^
      area.hashCode ^
      radius.hashCode ^
      mandatory.hashCode ^
      sequence.hashCode ^
      checked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Checkpoint &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          point == other.point &&
          area == other.area &&
          radius == other.radius &&
          mandatory == other.mandatory &&
          sequence == other.sequence &&
          checked == other.checked;
}

@freezed
sealed class Command with _$Command {
  const Command._();

  /// 设置目标速度（米/秒）
  const factory Command.setTargetSpeed(double field0) = Command_SetTargetSpeed;

  /// 设置速度范围
  const factory Command.setSpeedRange({
    required double min,
    required double max,
  }) = Command_SetSpeedRange;

  /// 设置加速度（米/秒²）
  const factory Command.setAcceleration(double field0) =
      Command_SetAcceleration;

  /// 设置减速度（米/秒²）
  const factory Command.setDeceleration(double field0) =
      Command_SetDeceleration;

  /// 设置步频（步/分钟）
  const factory Command.setStepFrequency(double field0) =
      Command_SetStepFrequency;

  /// 设置步幅（米）
  const factory Command.setStrideLength(double field0) =
      Command_SetStrideLength;

  /// 暂停模拟
  const factory Command.pause() = Command_Pause;

  /// 恢复模拟
  const factory Command.resume() = Command_Resume;

  /// 立即停止模拟
  const factory Command.stopImmediately() = Command_StopImmediately;

  /// N帧后延迟停止
  const factory Command.stopAfterFrames({
    required int frames,
    required bool graceful,
  }) = Command_StopAfterFrames;

  /// N秒后延迟停止
  const factory Command.stopAfterTime({
    required double seconds,
    required bool graceful,
  }) = Command_StopAfterTime;

  /// 跳转到指定位置（轨迹进度）
  const factory Command.jumpToProgress(double field0) = Command_JumpToProgress;

  /// 跳转到下一个轨迹
  const factory Command.nextTrajectory() = Command_NextTrajectory;

  /// 添加打卡点
  const factory Command.addCheckpoint(Checkpoint field0) =
      Command_AddCheckpoint;

  /// 移除打卡点
  const factory Command.removeCheckpoint(String field0) =
      Command_RemoveCheckpoint;

  /// 清除所有打卡点
  const factory Command.clearCheckpoints() = Command_ClearCheckpoints;

  /// 重置打卡状态
  const factory Command.resetCheckpointStatus() = Command_ResetCheckpointStatus;

  /// 设置抖动参数
  const factory Command.setJitterParams({
    double? positionAmplitude,
    double? speedAmplitude,
    double? bearingAmplitude,
  }) = Command_SetJitterParams;

  /// 设置刷新率
  const factory Command.setRefreshRate({
    double? gps,
    double? accelerometer,
    double? gyroscope,
    double? compass,
    double? barometer,
  }) = Command_SetRefreshRate;

  /// 设置围栏警告距离
  const factory Command.setFenceWarningDistance(double field0) =
      Command_SetFenceWarningDistance;

  /// 切换轨迹
  const factory Command.switchTrajectory({
    required BigInt index,
    required bool seamless,
  }) = Command_SwitchTrajectory;

  /// 追加轨迹
  const factory Command.appendTrajectory(Trajectory field0) =
      Command_AppendTrajectory;

  /// 自定义指令（JSON格式）
  const factory Command.custom(String field0) = Command_Custom;
}

/// 指令执行结果
class CommandResult {
  /// 是否成功
  final bool success;

  /// 结果消息
  final String message;

  /// 额外数据（JSON格式）
  final String? data;

  const CommandResult({
    required this.success,
    required this.message,
    this.data,
  });

  @override
  int get hashCode => success.hashCode ^ message.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommandResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          message == other.message &&
          data == other.data;
}

/// 指南针数据
class CompassData {
  /// 磁北方向（度）
  final double magneticHeading;

  /// 真北方向（度）
  final double trueHeading;

  /// 磁偏角（度）
  final double declination;

  /// X轴磁场强度（微特斯拉）
  final double magneticFieldX;

  /// Y轴磁场强度（微特斯拉）
  final double magneticFieldY;

  /// Z轴磁场强度（微特斯拉）
  final double magneticFieldZ;

  const CompassData({
    required this.magneticHeading,
    required this.trueHeading,
    required this.declination,
    required this.magneticFieldX,
    required this.magneticFieldY,
    required this.magneticFieldZ,
  });

  @override
  int get hashCode =>
      magneticHeading.hashCode ^
      trueHeading.hashCode ^
      declination.hashCode ^
      magneticFieldX.hashCode ^
      magneticFieldY.hashCode ^
      magneticFieldZ.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompassData &&
          runtimeType == other.runtimeType &&
          magneticHeading == other.magneticHeading &&
          trueHeading == other.trueHeading &&
          declination == other.declination &&
          magneticFieldX == other.magneticFieldX &&
          magneticFieldY == other.magneticFieldY &&
          magneticFieldZ == other.magneticFieldZ;
}

/// 地理坐标点（WGS84坐标系）
class GeoPoint {
  /// 纬度 (-90 到 90)
  final double latitude;

  /// 经度 (-180 到 180)
  final double longitude;

  /// 海拔高度（米）
  final double? altitude;

  const GeoPoint({
    required this.latitude,
    required this.longitude,
    this.altitude,
  });

  @override
  int get hashCode =>
      latitude.hashCode ^ longitude.hashCode ^ altitude.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GeoPoint &&
          runtimeType == other.runtimeType &&
          latitude == other.latitude &&
          longitude == other.longitude &&
          altitude == other.altitude;
}

/// GPS数据
class GpsData {
  /// 当前位置
  final GeoPoint position;

  /// 当前速度（米/秒）
  final double speed;

  /// 当前方向（度，0-360）
  final double bearing;

  /// 水平精度（米）
  final double horizontalAccuracy;

  /// 垂直精度（米）
  final double verticalAccuracy;

  /// 卫星数量
  final int satelliteCount;

  const GpsData({
    required this.position,
    required this.speed,
    required this.bearing,
    required this.horizontalAccuracy,
    required this.verticalAccuracy,
    required this.satelliteCount,
  });

  @override
  int get hashCode =>
      position.hashCode ^
      speed.hashCode ^
      bearing.hashCode ^
      horizontalAccuracy.hashCode ^
      verticalAccuracy.hashCode ^
      satelliteCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GpsData &&
          runtimeType == other.runtimeType &&
          position == other.position &&
          speed == other.speed &&
          bearing == other.bearing &&
          horizontalAccuracy == other.horizontalAccuracy &&
          verticalAccuracy == other.verticalAccuracy &&
          satelliteCount == other.satelliteCount;
}

/// 陀螺仪数据
class GyroscopeData {
  /// X轴角速度（度/秒）
  final double x;

  /// Y轴角速度（度/秒）
  final double y;

  /// Z轴角速度（度/秒）
  final double z;

  const GyroscopeData({required this.x, required this.y, required this.z});

  @override
  int get hashCode => x.hashCode ^ y.hashCode ^ z.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GyroscopeData &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          z == other.z;
}

/// 运动阶段
enum MovementPhase {
  /// 静止
  stationary,

  /// 起跑加速
  accelerating,

  /// 巡航
  cruising,

  /// 减速
  decelerating,

  /// 转向
  turning,

  /// 打卡中
  checkpoint,
}

/// 计步器数据
class PedometerData {
  /// 总步数
  final BigInt totalSteps;

  /// 当前步频（步/分钟）
  final double currentStepFrequency;

  /// 当前步幅（米）
  final double currentStrideLength;

  /// 本次跑步距离（米）
  final double distance;

  const PedometerData({
    required this.totalSteps,
    required this.currentStepFrequency,
    required this.currentStrideLength,
    required this.distance,
  });

  @override
  int get hashCode =>
      totalSteps.hashCode ^
      currentStepFrequency.hashCode ^
      currentStrideLength.hashCode ^
      distance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PedometerData &&
          runtimeType == other.runtimeType &&
          totalSteps == other.totalSteps &&
          currentStepFrequency == other.currentStepFrequency &&
          currentStrideLength == other.currentStrideLength &&
          distance == other.distance;
}

/// 多边形区域（用于电子围栏和禁跑区）
class Polygon {
  /// 多边形顶点
  final List<GeoPoint> points;

  const Polygon({required this.points});

  @override
  int get hashCode => points.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Polygon &&
          runtimeType == other.runtimeType &&
          points == other.points;
}

/// 传感器数据包
class SensorData {
  /// 时间戳（毫秒）
  final PlatformInt64 timestamp;

  /// GPS数据
  final GpsData? gps;

  /// 加速度计数据
  final AccelerometerData? accelerometer;

  /// 陀螺仪数据
  final GyroscopeData? gyroscope;

  /// 指南针数据
  final CompassData? compass;

  /// 气压计数据
  final BarometerData? barometer;

  /// 计步数据
  final PedometerData? pedometer;

  const SensorData({
    required this.timestamp,
    this.gps,
    this.accelerometer,
    this.gyroscope,
    this.compass,
    this.barometer,
    this.pedometer,
  });

  @override
  int get hashCode =>
      timestamp.hashCode ^
      gps.hashCode ^
      accelerometer.hashCode ^
      gyroscope.hashCode ^
      compass.hashCode ^
      barometer.hashCode ^
      pedometer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SensorData &&
          runtimeType == other.runtimeType &&
          timestamp == other.timestamp &&
          gps == other.gps &&
          accelerometer == other.accelerometer &&
          gyroscope == other.gyroscope &&
          compass == other.compass &&
          barometer == other.barometer &&
          pedometer == other.pedometer;
}

/// 模拟器配置
class SimulatorConfig {
  /// 目标速度（米/秒）
  final double targetSpeed;

  /// 最小速度（米/秒）
  final double minSpeed;

  /// 最大速度（米/秒）
  final double maxSpeed;

  /// 起跑加速度（米/秒²）
  final double acceleration;

  /// 减速度（米/秒²）
  final double deceleration;

  /// 步频（步/分钟）
  final double stepFrequency;

  /// 步幅（米）
  final double strideLength;

  /// GPS刷新率
  final double gpsRefreshRate;

  /// 加速度计刷新率
  final double accelerometerRefreshRate;

  /// 陀螺仪刷新率
  final double gyroscopeRefreshRate;

  /// 指南针刷新率
  final double compassRefreshRate;

  /// 气压计刷新率
  final double barometerRefreshRate;

  /// 抖动种子
  final BigInt jitterSeed;

  /// 位置抖动幅度（米）
  final double positionJitterAmplitude;

  /// 速度抖动幅度（米/秒）
  final double speedJitterAmplitude;

  /// 方向抖动幅度（度）
  final double bearingJitterAmplitude;

  /// 加速度抖动幅度（米/秒²）
  final double accelerometerJitterAmplitude;

  /// 陀螺仪抖动幅度（度/秒）
  final double gyroscopeJitterAmplitude;

  /// 抖动频率缩放
  final double jitterFrequencyScale;

  /// 轨迹播放模式
  final TrajectoryMode trajectoryMode;

  /// 循环次数（0表示无限循环）
  final int loopCount;

  /// 电子围栏（必须在区域内）
  final Polygon? geofence;

  /// 禁跑区（必须不在区域内）
  final List<Polygon> forbiddenZones;
  final double fenceWarningDistance;

  /// 预设打卡点列表
  final List<Checkpoint> checkpoints;

  /// 打卡点偏差容忍度（米）
  final double checkpointTolerance;

  /// 是否自动调整路径经过打卡点
  final bool autoRouteToCheckpoint;

  /// 打卡点停留时间（秒）
  final double checkpointStayTime;

  /// A* 寻路网格分辨率（米）
  final double pathfindingGridResolution;

  /// 平滑因子
  final double smoothingFactor;

  /// 海拔基准（米）
  final double baseAltitude;

  /// 海拔变化幅度（米）
  final double altitudeVariation;

  const SimulatorConfig({
    required this.targetSpeed,
    required this.minSpeed,
    required this.maxSpeed,
    required this.acceleration,
    required this.deceleration,
    required this.stepFrequency,
    required this.strideLength,
    required this.gpsRefreshRate,
    required this.accelerometerRefreshRate,
    required this.gyroscopeRefreshRate,
    required this.compassRefreshRate,
    required this.barometerRefreshRate,
    required this.jitterSeed,
    required this.positionJitterAmplitude,
    required this.speedJitterAmplitude,
    required this.bearingJitterAmplitude,
    required this.accelerometerJitterAmplitude,
    required this.gyroscopeJitterAmplitude,
    required this.jitterFrequencyScale,
    required this.trajectoryMode,
    required this.loopCount,
    this.geofence,
    required this.forbiddenZones,
    required this.fenceWarningDistance,
    required this.checkpoints,
    required this.checkpointTolerance,
    required this.autoRouteToCheckpoint,
    required this.checkpointStayTime,
    required this.pathfindingGridResolution,
    required this.smoothingFactor,
    required this.baseAltitude,
    required this.altitudeVariation,
  });

  @override
  int get hashCode =>
      targetSpeed.hashCode ^
      minSpeed.hashCode ^
      maxSpeed.hashCode ^
      acceleration.hashCode ^
      deceleration.hashCode ^
      stepFrequency.hashCode ^
      strideLength.hashCode ^
      gpsRefreshRate.hashCode ^
      accelerometerRefreshRate.hashCode ^
      gyroscopeRefreshRate.hashCode ^
      compassRefreshRate.hashCode ^
      barometerRefreshRate.hashCode ^
      jitterSeed.hashCode ^
      positionJitterAmplitude.hashCode ^
      speedJitterAmplitude.hashCode ^
      bearingJitterAmplitude.hashCode ^
      accelerometerJitterAmplitude.hashCode ^
      gyroscopeJitterAmplitude.hashCode ^
      jitterFrequencyScale.hashCode ^
      trajectoryMode.hashCode ^
      loopCount.hashCode ^
      geofence.hashCode ^
      forbiddenZones.hashCode ^
      fenceWarningDistance.hashCode ^
      checkpoints.hashCode ^
      checkpointTolerance.hashCode ^
      autoRouteToCheckpoint.hashCode ^
      checkpointStayTime.hashCode ^
      pathfindingGridResolution.hashCode ^
      smoothingFactor.hashCode ^
      baseAltitude.hashCode ^
      altitudeVariation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimulatorConfig &&
          runtimeType == other.runtimeType &&
          targetSpeed == other.targetSpeed &&
          minSpeed == other.minSpeed &&
          maxSpeed == other.maxSpeed &&
          acceleration == other.acceleration &&
          deceleration == other.deceleration &&
          stepFrequency == other.stepFrequency &&
          strideLength == other.strideLength &&
          gpsRefreshRate == other.gpsRefreshRate &&
          accelerometerRefreshRate == other.accelerometerRefreshRate &&
          gyroscopeRefreshRate == other.gyroscopeRefreshRate &&
          compassRefreshRate == other.compassRefreshRate &&
          barometerRefreshRate == other.barometerRefreshRate &&
          jitterSeed == other.jitterSeed &&
          positionJitterAmplitude == other.positionJitterAmplitude &&
          speedJitterAmplitude == other.speedJitterAmplitude &&
          bearingJitterAmplitude == other.bearingJitterAmplitude &&
          accelerometerJitterAmplitude == other.accelerometerJitterAmplitude &&
          gyroscopeJitterAmplitude == other.gyroscopeJitterAmplitude &&
          jitterFrequencyScale == other.jitterFrequencyScale &&
          trajectoryMode == other.trajectoryMode &&
          loopCount == other.loopCount &&
          geofence == other.geofence &&
          forbiddenZones == other.forbiddenZones &&
          fenceWarningDistance == other.fenceWarningDistance &&
          checkpoints == other.checkpoints &&
          checkpointTolerance == other.checkpointTolerance &&
          autoRouteToCheckpoint == other.autoRouteToCheckpoint &&
          checkpointStayTime == other.checkpointStayTime &&
          pathfindingGridResolution == other.pathfindingGridResolution &&
          smoothingFactor == other.smoothingFactor &&
          baseAltitude == other.baseAltitude &&
          altitudeVariation == other.altitudeVariation;
}

@freezed
sealed class SimulatorEvent with _$SimulatorEvent {
  const SimulatorEvent._();

  /// 模拟开始
  const factory SimulatorEvent.started() = SimulatorEvent_Started;

  /// 模拟暂停
  const factory SimulatorEvent.paused() = SimulatorEvent_Paused;

  /// 模拟恢复
  const factory SimulatorEvent.resumed() = SimulatorEvent_Resumed;

  /// 模拟停止
  const factory SimulatorEvent.stopped({required StopReason reason}) =
      SimulatorEvent_Stopped;

  /// 传感器数据更新
  const factory SimulatorEvent.sensorDataUpdated({required SensorData data}) =
      SimulatorEvent_SensorDataUpdated;

  /// 位置更新
  const factory SimulatorEvent.positionUpdated({
    required GeoPoint position,
    required double speed,
    required double bearing,
  }) = SimulatorEvent_PositionUpdated;

  /// 速度变化
  const factory SimulatorEvent.speedChanged({
    required double oldSpeed,
    required double newSpeed,
  }) = SimulatorEvent_SpeedChanged;

  /// 运动阶段变化
  const factory SimulatorEvent.phaseChanged({
    required MovementPhase oldPhase,
    required MovementPhase newPhase,
  }) = SimulatorEvent_PhaseChanged;

  /// 轨迹切换
  const factory SimulatorEvent.trajectorySwitched({
    required BigInt index,
    required String trajectoryId,
  }) = SimulatorEvent_TrajectorySwitched;

  /// 打卡成功
  const factory SimulatorEvent.checkpointReached({
    required Checkpoint checkpoint,
  }) = SimulatorEvent_CheckpointReached;

  /// 所有打卡完成
  const factory SimulatorEvent.allCheckpointsCompleted() =
      SimulatorEvent_AllCheckpointsCompleted;

  /// 进入电子围栏边界
  const factory SimulatorEvent.geofenceEntered() =
      SimulatorEvent_GeofenceEntered;

  /// 离开电子围栏
  const factory SimulatorEvent.geofenceExited() = SimulatorEvent_GeofenceExited;

  /// 进入禁跑区
  const factory SimulatorEvent.forbiddenZoneEntered({
    required BigInt zoneIndex,
  }) = SimulatorEvent_ForbiddenZoneEntered;

  /// 离开禁跑区
  const factory SimulatorEvent.forbiddenZoneExited({
    required BigInt zoneIndex,
  }) = SimulatorEvent_ForbiddenZoneExited;

  /// 错误发生
  const factory SimulatorEvent.errorOccurred({required String message}) =
      SimulatorEvent_ErrorOccurred;
}

/// 模拟器状态
enum SimulatorState {
  /// 空闲状态
  idle,

  /// 准备中
  preparing,

  /// 运行中
  running,

  /// 暂停
  paused,

  /// 停止中
  stopping,

  /// 已停止
  stopped,

  /// 错误
  error,
}

/// 模拟器统计信息
class SimulatorStats {
  /// 运行时长（毫秒）
  final BigInt elapsedTimeMs;

  /// 总模拟距离（米）
  final double totalDistance;

  /// 当前速度（米/秒）
  final double currentSpeed;

  /// 平均速度（米/秒）
  final double averageSpeed;

  /// 消耗卡路里
  final double calories;

  /// 总步数
  final BigInt totalSteps;

  /// 当前轨迹索引
  final BigInt currentTrajectoryIndex;

  /// 当前轨迹进度（0.0-1.0）
  final double trajectoryProgress;

  /// 已完成打卡点数
  final int checkedPoints;

  /// 当前运动阶段
  final MovementPhase currentPhase;

  /// 当前位置
  final GeoPoint? currentPosition;

  const SimulatorStats({
    required this.elapsedTimeMs,
    required this.totalDistance,
    required this.currentSpeed,
    required this.averageSpeed,
    required this.calories,
    required this.totalSteps,
    required this.currentTrajectoryIndex,
    required this.trajectoryProgress,
    required this.checkedPoints,
    required this.currentPhase,
    this.currentPosition,
  });

  @override
  int get hashCode =>
      elapsedTimeMs.hashCode ^
      totalDistance.hashCode ^
      currentSpeed.hashCode ^
      averageSpeed.hashCode ^
      calories.hashCode ^
      totalSteps.hashCode ^
      currentTrajectoryIndex.hashCode ^
      trajectoryProgress.hashCode ^
      checkedPoints.hashCode ^
      currentPhase.hashCode ^
      currentPosition.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimulatorStats &&
          runtimeType == other.runtimeType &&
          elapsedTimeMs == other.elapsedTimeMs &&
          totalDistance == other.totalDistance &&
          currentSpeed == other.currentSpeed &&
          averageSpeed == other.averageSpeed &&
          calories == other.calories &&
          totalSteps == other.totalSteps &&
          currentTrajectoryIndex == other.currentTrajectoryIndex &&
          trajectoryProgress == other.trajectoryProgress &&
          checkedPoints == other.checkedPoints &&
          currentPhase == other.currentPhase &&
          currentPosition == other.currentPosition;
}

@freezed
sealed class SimulatorUpdate with _$SimulatorUpdate {
  const SimulatorUpdate._();

  const factory SimulatorUpdate.event(SimulatorEvent field0) =
      SimulatorUpdate_Event;
  const factory SimulatorUpdate.sensorData(SensorData field0) =
      SimulatorUpdate_SensorData;
}

/// 停止原因
enum StopReason {
  /// 正常结束
  normal,

  /// 用户请求
  userRequested,

  /// 超出电子围栏
  geofenceViolation,

  /// 进入禁跑区
  forbiddenZoneViolation,

  /// 错误
  error,

  /// 帧数或时间限制
  limit,
}

/// 轨迹数据
class Trajectory {
  /// 轨迹ID
  final String id;

  /// 轨迹名称
  final String? name;

  /// 轨迹点列表
  final List<GeoPoint> points;

  const Trajectory({required this.id, this.name, required this.points});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ points.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Trajectory &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          points == other.points;
}

/// 轨迹播放模式
enum TrajectoryMode {
  /// 单条轨迹循环播放
  loop,

  /// 多条轨迹顺序播放
  sequential,

  /// 多条轨迹随机播放
  random,
}
