// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// VPN 配置
class VpnConfig {
  final String server;
  final String username;
  final String password;
  final String totpSecret;

  /// 自定义 DNS 服务器（可选，不填则使用 VPN 分配的）
  final String? customDns;

  /// TUN 设备名称（可选）
  final String? tunName;

  /// TUN 设备 IP 地址
  final String tunAddress;

  /// TUN 设备子网掩码
  final String tunNetmask;

  /// MTU
  final int mtu;

  /// 分流路由（CIDR 列表，逗号分隔，如 "10.0.0.0/8,192.168.0.0/16"）
  /// 为空则默认路由所有流量走 VPN
  final String? splitRoutes;

  const VpnConfig({
    required this.server,
    required this.username,
    required this.password,
    required this.totpSecret,
    this.customDns,
    this.tunName,
    required this.tunAddress,
    required this.tunNetmask,
    required this.mtu,
    this.splitRoutes,
  });

  @override
  int get hashCode =>
      server.hashCode ^
      username.hashCode ^
      password.hashCode ^
      totpSecret.hashCode ^
      customDns.hashCode ^
      tunName.hashCode ^
      tunAddress.hashCode ^
      tunNetmask.hashCode ^
      mtu.hashCode ^
      splitRoutes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VpnConfig &&
          runtimeType == other.runtimeType &&
          server == other.server &&
          username == other.username &&
          password == other.password &&
          totpSecret == other.totpSecret &&
          customDns == other.customDns &&
          tunName == other.tunName &&
          tunAddress == other.tunAddress &&
          tunNetmask == other.tunNetmask &&
          mtu == other.mtu &&
          splitRoutes == other.splitRoutes;
}

/// VPN 连接状态
enum VpnState {
  disconnected,
  connecting,
  loginStart,
  loginPassword,
  waitingSms,
  waitingTotp,
  gettingToken,
  gettingResources,
  gettingIp,
  openingChannels,
  connected,
  error,
}

/// VPN traffic statistics
class VpnTrafficStats {
  final BigInt bytesSent;
  final BigInt bytesReceived;
  final BigInt packetsSent;
  final BigInt packetsReceived;

  const VpnTrafficStats({
    required this.bytesSent,
    required this.bytesReceived,
    required this.packetsSent,
    required this.packetsReceived,
  });

  @override
  int get hashCode =>
      bytesSent.hashCode ^
      bytesReceived.hashCode ^
      packetsSent.hashCode ^
      packetsReceived.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VpnTrafficStats &&
          runtimeType == other.runtimeType &&
          bytesSent == other.bytesSent &&
          bytesReceived == other.bytesReceived &&
          packetsSent == other.packetsSent &&
          packetsReceived == other.packetsReceived;
}
