import 'package:punklorde/src/rust/services/motion_sim/model.dart';

final SimulatorConfig defaultSimulatorConfig = SimulatorConfig(
  targetSpeed: 3.0,
  minSpeed: 2.9,
  maxSpeed: 3.2,
  acceleration: 3.0,
  deceleration: 3.0,
  stepFrequency: 150,
  strideLength: 0.8,
  gpsRefreshRate: 1,
  accelerometerRefreshRate: 1.0,
  gyroscopeRefreshRate: 1.0,
  compassRefreshRate: 1.0,
  barometerRefreshRate: 1.0,
  jitterSeed: BigInt.from(33550336),
  positionJitterAmplitude: 1.0,
  speedJitterAmplitude: 0.5,
  bearingJitterAmplitude: 5.0,
  accelerometerJitterAmplitude: 0.5,
  gyroscopeJitterAmplitude: 2.0,
  jitterFrequencyScale: 1.0,
  trajectoryMode: .loop,
  loopCount: 0,
  forbiddenZones: [],
  fenceWarningDistance: 3.0,
  checkpoints: [],
  checkpointTolerance: 5,
  autoRouteToCheckpoint: false,
  checkpointStayTime: 0,
  pathfindingGridResolution: 10,
  smoothingFactor: 0.5,
  baseAltitude: 400,
  altitudeVariation: 1.0,
);
