// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../services/motion_sim/model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SIMULATORS`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

/// 创建模拟器，返回句柄ID（字符串）
String createSimulator({
  required SimulatorConfig config,
  required List<Trajectory> trajectories,
}) => RustLib.instance.api.crateApiMotionSimCreateSimulator(
  config: config,
  trajectories: trajectories,
);

/// 订阅模拟器的数据流，返回 Dart Stream<SimulatorUpdate>
Future<Stream<SimulatorUpdate>> subscribeSimulator({
  required String handleId,
}) => RustLib.instance.api.crateApiMotionSimSubscribeSimulator(
  handleId: handleId,
);

/// 启动模拟器
void startSimulator({required String handleId}) =>
    RustLib.instance.api.crateApiMotionSimStartSimulator(handleId: handleId);

/// 暂停模拟器
void pauseSimulator({required String handleId}) =>
    RustLib.instance.api.crateApiMotionSimPauseSimulator(handleId: handleId);

/// 恢复模拟器
void resumeSimulator({required String handleId}) =>
    RustLib.instance.api.crateApiMotionSimResumeSimulator(handleId: handleId);

/// 停止模拟器
void stopSimulator({required String handleId, required StopReason reason}) =>
    RustLib.instance.api.crateApiMotionSimStopSimulator(
      handleId: handleId,
      reason: reason,
    );

/// 更新模拟器（每帧调用）
SensorData? updateSimulator({required String handleId, required double dt}) =>
    RustLib.instance.api.crateApiMotionSimUpdateSimulator(
      handleId: handleId,
      dt: dt,
    );

/// 执行指令
CommandResult executeCommand({
  required String handleId,
  required Command command,
}) => RustLib.instance.api.crateApiMotionSimExecuteCommand(
  handleId: handleId,
  command: command,
);

/// 获取模拟器状态
SimulatorState? getState({required String handleId}) =>
    RustLib.instance.api.crateApiMotionSimGetState(handleId: handleId);

/// 获取统计信息
SimulatorStats? getStats({required String handleId}) =>
    RustLib.instance.api.crateApiMotionSimGetStats(handleId: handleId);

/// 获取配置
SimulatorConfig? getConfig({required String handleId}) =>
    RustLib.instance.api.crateApiMotionSimGetConfig(handleId: handleId);

/// 释放模拟器（从全局map中移除）
void disposeSimulator({required String handleId}) =>
    RustLib.instance.api.crateApiMotionSimDisposeSimulator(handleId: handleId);
