// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../services/sangfor.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `VPN_SERVICES`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

/// Create a new VPN service, returns opaque handle ID
String createVpn({required VpnConfig config}) =>
    RustLib.instance.api.crateApiSangforCreateVpn(config: config);

/// Start VPN connection
void connectVpn({required String handleId}) =>
    RustLib.instance.api.crateApiSangforConnectVpn(handleId: handleId);

/// Phase 1: Authenticate and retrieve the server-assigned IP.
///
/// This blocks the calling thread during network I/O (typically 2-5 seconds).
/// Returns the server-assigned IP string on success.
/// Returns Err("SMS_REQUIRED") or Err("TOTP_REQUIRED") if 2FA is needed.
/// After 2FA, call `continue_vpn_auth_and_get_ip()` to finish auth and get the IP.
///
/// Use the returned IP to configure the TUN device (Android VpnService).
/// Then call `open_vpn_channels_and_relay()` to start the VPN data relay.
String authenticateVpnAndGetIp({required String handleId}) => RustLib
    .instance
    .api
    .crateApiSangforAuthenticateVpnAndGetIp(handleId: handleId);

/// Continue authentication after 2FA code submission.
///
/// Call this after the user provides their SMS/TOTP code.
/// Returns the server-assigned IP string on success.
/// Then call `open_vpn_channels_and_relay()` to start the VPN data relay.
String continueVpnAuthAndGetIp({
  required String handleId,
  required String code,
}) => RustLib.instance.api.crateApiSangforContinueVpnAuthAndGetIp(
  handleId: handleId,
  code: code,
);

/// Phase 2: Open data channels and start TUN relay.
///
/// Must be called after:
/// 1. `authenticate_vpn_and_get_ip()` (or `continue_vpn_auth_and_get_ip()`) succeeded
/// 2. On Android: `set_tun_fd()` was called with the TUN fd
///
/// This method spawns a background thread for the relay and returns immediately.
void openVpnChannelsAndRelay({required String handleId}) => RustLib.instance.api
    .crateApiSangforOpenVpnChannelsAndRelay(handleId: handleId);

/// Get the server-assigned IP (if authentication has completed).
/// Returns None if the IP has not been retrieved yet.
String? getVpnAssignedIp({required String handleId}) =>
    RustLib.instance.api.crateApiSangforGetVpnAssignedIp(handleId: handleId);

/// Submit 2FA code (SMS or TOTP)
void submit2Fa({required String handleId, required String code}) => RustLib
    .instance
    .api
    .crateApiSangforSubmit2Fa(handleId: handleId, code: code);

/// Disconnect VPN
void disconnectVpn({required String handleId}) =>
    RustLib.instance.api.crateApiSangforDisconnectVpn(handleId: handleId);

/// On Android, set the TUN file descriptor from VpnService.establish().
/// Must be called before connect_vpn() on Android targets.
/// On non-Android targets, this is a no-op (fd is ignored).
void setTunFd({required String handleId, required int fd}) =>
    RustLib.instance.api.crateApiSangforSetTunFd(handleId: handleId, fd: fd);

/// Get current VPN state
VpnState? getVpnState({required String handleId}) =>
    RustLib.instance.api.crateApiSangforGetVpnState(handleId: handleId);

/// Get VPN config
VpnConfig? getVpnConfig({required String handleId}) =>
    RustLib.instance.api.crateApiSangforGetVpnConfig(handleId: handleId);

/// Check if VPN is running
bool? isVpnRunning({required String handleId}) =>
    RustLib.instance.api.crateApiSangforIsVpnRunning(handleId: handleId);

/// Get VPN traffic statistics
VpnTrafficStats? getVpnTrafficStats({required String handleId}) =>
    RustLib.instance.api.crateApiSangforGetVpnTrafficStats(handleId: handleId);

/// Get the last error message from VPN service
String? getVpnLastError({required String handleId}) =>
    RustLib.instance.api.crateApiSangforGetVpnLastError(handleId: handleId);

/// Subscribe to VPN state changes
Future<Stream<VpnState>> subscribeVpnState({required String handleId}) =>
    RustLib.instance.api.crateApiSangforSubscribeVpnState(handleId: handleId);

/// Dispose VPN service
void disposeVpn({required String handleId}) =>
    RustLib.instance.api.crateApiSangforDisposeVpn(handleId: handleId);
